;;; config.el -*- lexical-binding: t; -*-

(defadvice! +my/literate-tangle-only-config-a (&rest _)
  "Tangle on save only for `+literate-config-file' itself.

Doom's own `+literate-recompile-maybe-h' fires for *any* org file under
`doom-user-dir', and this repo keeps `PROJECT.org' and all of `docs/*.org'
there -- so saving a 6000-line ADR file would spawn a full retangle."
  :override #'+literate-recompile-maybe-h
  (when (and buffer-file-name
             (file-equal-p (buffer-file-name (buffer-base-buffer))
                           (file-truename +literate-config-file)))
    (+literate-tangle-h)))

(defadvice! +my/block-worktree-tangle-a (orig-fn &rest args)
  "Refuse to tangle a `config.org' that isn't the primary checkout's.

`+my/literate-tangle-only-config-a' above only covers tangle-on-*save*
\(Doom's `after-save-hook' path\). It does nothing for the interactive
`C-c C-v t' / `org-babel-tangle' path, which is a separate code path
entirely. Without this second guard, manually tangling a git worktree's
`config.org' would still write the real `~/.bashrc', `~/.inputrc',
`~/.gitconfig' and `~/.local/bin/pass-backup' from a half-finished branch,
because $HOME is shared across every worktree while the checkout is not.
Defense-in-depth for the zettelkasten-integration work's worktree plan --
ordinary tangling of the primary checkout is unaffected."
  :around #'org-babel-tangle
  (if (and buffer-file-name
           (string= (file-name-nondirectory buffer-file-name) "config.org")
           (not (file-equal-p (file-truename buffer-file-name)
                              (file-truename +literate-config-file))))
      (user-error "Refusing to tangle %s: not the primary checkout's config.org"
                  buffer-file-name)
    (apply orig-fn args)))

;;; $DOOMDIR/config.el -*- lexical-binding: t; -*-

;; Place your private configuration here! Remember, you do not need to run 'doom
;; sync' after modifying this file!

;; Doom's env cache (05-doom-env.load.el, regenerated by `doom sync --env')
;; loads unconditionally on every startup, before this file. If it was ever
;; regenerated from inside a Claude Code CLI subprocess shell (which any
;; agent's shell always is), it bakes in that shell's ephemeral,
;; subprocess-only Claude Code identity vars (CLAUDECODE, CLAUDE_JOB_DIR,
;; CLAUDE_CODE_SESSION_ID, etc.) as permanent config, so every `claude'
;; process later launched from Emacs (e.g. via claude-code-ide.el) inherits a
;; dead session's identity instead of a fresh one. Since this file is the one
;; thing Doom loads last, every startup, regardless of what's cached, strip
;; those vars here defensively rather than relying on the cache staying
;; clean. See docs/decisions.org ADR-013 and
;; docs/ai/troubleshooting.org::tshoot-claude-env-leak for the full incident.
(setq process-environment
      (seq-remove
       (lambda (entry) (string-match-p "\\`\\(CLAUDECODE\\|CLAUDE_[A-Z_]*\\|AI_AGENT\\)=" entry))
       process-environment))


;; Some functionality uses this to identify you, e.g. GPG configuration, email
;; clients, file templates and snippets. It is optional.
;; (setq user-full-name "John Doe"
;;       user-mail-address "john@doe.com")

;; Doom exposes five (optional) variables for controlling fonts in Doom:
;;
;; - `doom-font' -- the primary font to use
;; - `doom-variable-pitch-font' -- a non-monospace font (where applicable)
;; - `doom-big-font' -- used for `doom-big-font-mode'; use this for
;;   presentations or streaming.
;; - `doom-symbol-font' -- for symbols
;; - `doom-serif-font' -- for the `fixed-pitch-serif' face
;;
;; See 'C-h v doom-font' for documentation and more examples of what they
;; accept. For example:
;;
;;(setq doom-font (font-spec :family "Fira Code" :size 12 :weight 'semi-light)
;;      doom-variable-pitch-font (font-spec :family "Fira Sans" :size 13))
;;
;; If you or Emacs can't find your font, use 'M-x describe-font' to look them
;; up, `M-x eval-region' to execute elisp code, and 'M-x doom/reload-font' to
;; refresh your font settings. If Emacs still can't find your font, it likely
;; wasn't installed correctly. Font issues are rarely Doom issues!

;; There are two ways to load a theme. Both assume the theme is installed and
;; available. You can either set `doom-theme' or manually load a theme with the
;; `load-theme' function. This is the default:
(setq doom-theme 'doom-zenburn)

;; This determines the style of line numbers in effect. If set to `nil', line
;; numbers are disabled. For relative line numbers, set this to `relative'.
(setq display-line-numbers-type 'relative)

;; If you use `org' and don't want your org files in the default location below,
;; change `org-directory'. It must be set before org loads!
(setq org-directory "~/org/")


;; Whenever you reconfigure a package, make sure to wrap your config in an
;; `after!' block, otherwise Doom's defaults may override your settings. E.g.
;;
;;   (after! PACKAGE
;;     (setq x y))
;;
;; The exceptions to this rule:
;;
;;
;;   - Setting file/directory variables (like `org-directory')
;;   - Setting variables which explicitly tell you to set them before their
;;     package is loaded (see 'C-h v VARIABLE' to look up their documentation).
;;   - Setting doom variables (which start with 'doom-' or '+').
;;
;; Here are some additional functions/macros that will help you configure Doom.
;;
;; - `load!' for loading external *.el files relative to this one
;; - `use-package!' for configuring packages
;; - `after!' for running code after a package has loaded
;; - `add-load-path!' for adding directories to the `load-path', relative to
;;   this file. Emacs searches the `load-path' when you load packages with
;;   `require' or `use-package'.
;; - `map!' for binding new keys
;;
;; To get information about any of these functions/macros, move the cursor over
;; the highlighted symbol at press 'K' (non-evil users must press 'C-c c k').
;; This will open documentation for it, including demos of how they are used.
;; Alternatively, use `C-h o' to look up a symbol (functions, variables, faces,
;; etc).
;;
;; You can also try 'gd' (or 'C-c c d') to jump to their definition and see how
;; they are implemented.

;; Maximize every new graphical frame, and resize splash screen.
;;
;; Without `frame-resize-pixelwise', Emacs quantizes its frame to whole
;; character-cell dimensions any time the size changes -- including right
;; after the window manager maximizes it. On GNOME/Mutter (Ubuntu) that
;; immediate "round back down to a cell boundary" resize reads as the app
;; rejecting the maximize, so Mutter reverts the state instantly -- the frame
;; never visibly grows at all. xfwm4 (Xubuntu) tolerates the mismatch and
;; leaves it maximized regardless, which is why this only shows up on Ubuntu.
(setq frame-resize-pixelwise t)

;; Belt-and-suspenders: even with pixelwise resizing, GNOME/Mutter can still
;; ignore a `fullscreen' request sent right at frame creation (the frame
;; isn't mapped onto the display yet), unlike xfwm4, which applies it
;; immediately. Reasserting it a few times over the following moments is a
;; self-healing workaround -- setting `fullscreen' to a value it already has
;; is a no-op, so this is harmless once it "sticks". Hooking
;; `after-make-frame-functions' (rather than only
;; `server-after-make-frame-hook') also covers frames created outside the
;; emacsclient protocol, e.g. claude-code-ide.el's own frame.
(defun +my/maximize-frame (frame)
  (when (display-graphic-p frame)
    (dolist (delay '(0 0.1 0.3))
      (run-with-timer delay nil
                       (lambda ()
                         (when (frame-live-p frame)
                           (set-frame-parameter frame 'fullscreen 'maximized)))))))
(add-hook 'after-make-frame-functions #'+my/maximize-frame)

;; ROOT CAUSE (found 2026-08-17): `after-make-frame-functions' is documented
;; to never run for the very first frame of a session -- that frame already
;; exists before this hook is installed. So the maximize logic above only
;; ever ran for *subsequent* frames (emacsclient, claude-code-ide.el's own
;; frame, C-x 5 2) and never for the frame you actually see at startup --
;; confirmed live: zero `+my/maximize-frame' messages logged despite the
;; frame existing. None of the undecorated/pixelwise theories were it; the
;; startup frame's maximize call simply never fired. Call it directly once
;; that frame exists.
(add-hook 'window-setup-hook
          (lambda () (+my/maximize-frame (selected-frame))))

;; Only take over a bare `emacsclient -c' frame (e.g. a terminal alias that
;; pops a blank Emacs frame) with the dashboard -- never a frame that was
;; asked to visit a specific file, e.g. Magit's `git commit' opening
;; COMMIT_EDITMSG via `with-editor'/`emacsclient'. The guard has to inspect
;; FRAME's *window*, not `buffer-file-name': `select-frame'/
;; `with-selected-frame' select the frame (and its window), but do NOT
;; sync `current-buffer' to that window's buffer -- `buffer-file-name' here
;; reads whatever buffer happened to be current in this timer callback's
;; execution context, which has nothing to do with FRAME. Confirmed live
;; (2026-08-20): even with COMMIT_EDITMSG correctly showing in the frame,
;; `(with-selected-frame frame (unless buffer-file-name ...))' saw a
;; stale/unrelated current-buffer and opened the dashboard anyway. A prior
;; fix (69a66c2) added this timer+guard for the same symptom but checked
;; `buffer-file-name' the same wrong way, so it never actually worked --
;; see docs/ai/troubleshooting.org::tshoot-dashboard-stomps-commit-buffer.
(add-hook 'server-after-make-frame-hook
          (lambda ()
            (let ((frame (selected-frame)))
              (run-with-timer
               0.1 nil
               (lambda ()
                 (when (frame-live-p frame)
                   (unless (buffer-file-name
                            (window-buffer (frame-selected-window frame)))
                     (with-selected-frame frame
                       (+dashboard/open frame)))))))))

(add-to-list 'default-frame-alist '(undecorated . t))

;; Center text and limit line width for better readability
(use-package! perfect-margin
  :custom
  (perfect-margin-visible-width 100)  ; adjust to your preferred text column width
  :config
  (perfect-margin-mode t)
  (after! doom-modeline
    (setq mode-line-right-align-edge 'right-fringe)))

;; Better default behavior
;;     - No permanent deletion, use trash
;;     - Smoother scrolling
(setq delete-by-moving-to-trash t
      scroll-margin 0                  ; ultra-scroll (:ui smooth-scroll) requires 0
      scroll-conservatively 101)

;; Doom modeline mods
(after! doom-modeline
  ;; 1) Size / spacing
  (setq doom-modeline-height 28          ; modeline height (pixels-ish)
        doom-modeline-bar-width 3        ; left bar width
        doom-modeline-window-width-limit 85) ; hide extra info in narrow windows

  ;; 2) Icons (turn off if you want max speed / no nerd fonts)
  (setq doom-modeline-icon t
        doom-modeline-major-mode-icon t
        doom-modeline-major-mode-color-icon t)

  ;; 3) File name style (popular: show relative name from project)
  (setq doom-modeline-buffer-file-name-style 'relative-to-project)

  ;; 4) Common “noise” toggles
  (setq doom-modeline-minor-modes nil    ; hides minor modes list (usually noisy)
        doom-modeline-mu4e nil
        doom-modeline-gnus nil)

  ;; 5) Git + diagnostics (popular to keep on)
  (setq doom-modeline-vcs t
        doom-modeline-checker-simple-format t)

  ;; 6) Extra info (pick what you like)
  (setq doom-modeline-indent-info nil    ; show indent info (spaces/tabs)
        doom-modeline-buffer-encoding nil ; hide UTF-8, etc. (usually not needed)
        doom-modeline-time nil           ; set to t if you want a clock
        doom-modeline-battery nil))      ; set to t on laptops

;; Emacs 31.1 built-ins (docs/decisions.org ADR-037).

;; `trusted-content' (30.1) is an allowlist of files and directories whose
;; embedded code Emacs may evaluate without prompting -- it gates elisp Flymake
;; and local-variable evaluation, and exists because of CVE-2024-53920. It is
;; scoped here to exactly two trees rather than set to `:all': this repo, whose
;; config.org *is* the configuration and re-tangles on every save (ADR-035), and
;; the Org directory. Directory entries must be absolute and end in a slash.
(setq trusted-content
      (list (file-name-as-directory (expand-file-name "~/.config/doom"))
            (file-name-as-directory (expand-file-name "~/org"))))

;; `kill-region-dwim' (31.1): C-w with no active region kills the previous word
;; instead of signalling an error. Only reachable in Emacs state and the
;; minibuffer -- Evil owns C-w in insert state -- but harmless there and it
;; removes a papercut in `M-x' and `read-string' prompts.
(setq kill-region-dwim 'emacs-word)

;; `eldoc-help-at-pt' (31.1): surface `help-echo' text (Flycheck overlays, LSP
;; hovers, button help) through ElDoc instead of requiring a mouse hover.
(setq eldoc-help-at-pt t)

;; `split-window-preferred-direction' (31.1): when Emacs splits a window on its
;; own -- a popup that will not fit, `display-buffer' fallbacks -- split along
;; whichever axis has more room rather than always vertically.
(setq split-window-preferred-direction 'longest)

;; `minibuffer-regexp-mode' (31.1): syntax-highlight regexp metacharacters while
;; typing one in the minibuffer. Applies to `query-replace-regexp', `rgrep' and
;; Consult prompts alike; costs nothing and is on by default upstream.
(minibuffer-regexp-mode +1)

;; `find-function-mode' (31.1): installs C-x F / C-x V / C-x K (find function,
;; variable, key definition at point). Worth having in a config that is itself
;; several hundred lines of Elisp plus a large module tree to read.
(find-function-mode +1)

;; Hideshow gained fold affordances in 31.1. Doom's `:editor fold' dispatches
;; z-prefixed Evil keys across hideshow, vimish-fold and treesit-fold already,
;; so only the *display* halves are set here -- no new keybindings, because
;; `hs-cycle' would have to take TAB and TAB is a documented precedence chain
;; (docs/ai/keybindings.org): Copilot, then yasnippet, then Corfu, then NES.
(after! hideshow
  (setq hs-show-indicators t          ; fringe/margin marker on a folded region
        hs-display-lines-hidden t))   ; and a count of the lines it swallowed

;; --- Rice pass (docs/decisions.org ADR-022) -------------------------------
;; Theme stays doom-zenburn; this section covers font, transparency, cursor
;; motion feedback, zen-mode focus dimming, and the dashboard banner.

;; Font: "JetBrains Mono" (plain, via apt's `fonts-jetbrains-mono' -- the
;; Nerd-patched variant needed GitHub, which this sandbox couldn't reach) for
;; both faces; `:ui zen's mixed-pitch-mode wants a variable-pitch font to
;; switch to. Icon glyph coverage doesn't need the primary font itself to be
;; Nerd-patched: `Symbols Nerd Font Mono' (already installed, and exactly
;; what `nerd-icons.el' pairs with any regular font as a fallback) covers
;; that via Emacs's normal fontset fallback. `M-x describe-font' confirms
;; this actually took effect.
(setq doom-font (font-spec :family "JetBrains Mono" :size 13)
      doom-variable-pitch-font (font-spec :family "JetBrains Mono" :size 13))

;; Transparency: native Emacs 29+ alpha-background compositing -- no external
;; compositor needed (confirmed: this build is Cairo-enabled). Unfocused
;; frames fade further so the active window visually pops.
;; `after-focus-change-function' (not the obsolete-since-27.1
;; `focus-in-hook'/`focus-out-hook') is the correct modern hook, and it fires
;; per-frame-list rather than assuming a single frame, which matters here
;; since Emacs runs as a daemon with frames created via emacsclient.
(add-to-list 'default-frame-alist '(alpha-background . 92))
(defun +my/rice-update-frame-alpha ()
  "Fade every unfocused frame's alpha-background; keep the focused one clearer."
  (dolist (frame (frame-list))
    (set-frame-parameter frame 'alpha-background
                          (if (eq frame (selected-frame)) 92 80))))
(add-function :after after-focus-change-function #'+my/rice-update-frame-alpha)

;; Cursor motion feedback: pulsar (animated colored pulse) instead of Doom's
;; plain :ui nav-flash blink module (disabled in init.el) -- running both
;; would double-fire on the same events. Pulsar's own default
;; `pulsar-pulse-functions' already covers the common Evil big-motion
;; commands (evil-goto-line, evil-scroll-*, evil-window-top/bottom, etc.) and
;; `other-window' -- only `switch-to-buffer' was missing from that list.
(use-package! pulsar
  :hook (doom-first-input . pulsar-global-mode)
  :config
  (setq pulsar-delay 0.06
        pulsar-iterations 8
        pulsar-face 'pulsar-cyan)
  (add-to-list 'pulsar-pulse-functions 'switch-to-buffer))

;; Dashboard: ASCII banner spelling this machine's hostname, generated at
;; render time via `figlet' (a tiny, standard Unix tool -- matches this
;; config's existing pattern of shelling out to well-known external tools,
;; e.g. ruff/black/xdotool elsewhere in this file) rather than a hand-rolled
;; Elisp font table or a hardcoded name, so the banner stays correct if this
;; config is ever used on a different machine. Overrides
;; `+dashboard-ascii-banner-fn' (a doom `+' variable, so no `after!' wrapper
;; needed, matching the exemption already documented above). Falls back to
;; plain `(system-name)' text if `figlet' isn't installed, rather than
;; erroring the dashboard.
(defun +my/dashboard-hostname-banner-fn ()
  "Return an ASCII banner of `(system-name)', rendered via figlet."
  (propertize
   (if (executable-find "figlet")
       (string-trim-right
        (shell-command-to-string
         (format "figlet -f standard %s"
                 (shell-quote-argument (system-name)))))
     (system-name))
   'face '+dashboard-banner))
(setq +dashboard-ascii-banner-fn #'+my/dashboard-hostname-banner-fn)
;; --- end rice pass ---------------------------------------------------------

;; centaur-tabs' new-tab button (the `+' at the right end of the tab bar) and
;; its interactive equivalent both funnel through
;; `centaur-tabs--create-new-tab', which opens a blank "Untitled" buffer.
;; Override that single chokepoint so both entry points land on the Doom
;; dashboard instead -- the dashboard is already this config's fallback buffer
;; (`doom-fallback-buffer'), so a new tab and an emptied frame agree on what
;; "nothing open" looks like.
;;
;; The dashboard is a singleton buffer (`+dashboard-name', "*doom*"), so this
;; selects the existing dashboard tab rather than stacking up new ones; that's
;; deliberate, since `+dashboard-reload' renders into that one buffer.
(after! centaur-tabs
  (defun +my/centaur-tabs-new-tab-dashboard (&rest _)
    "Open the Doom dashboard instead of an Untitled buffer."
    (interactive)
    (+dashboard/open (selected-frame)))
  (advice-add 'centaur-tabs--create-new-tab :override
              #'+my/centaur-tabs-new-tab-dashboard)

  ;; Doom's `:ui tabs' module installs
  ;; `+tabs-disable-centaur-tabs-mode-maybe-h' on `+dashboard-mode-hook'; it
  ;; *enables* `centaur-tabs-local-mode' there, whose on-state means "hide
  ;; the bar in this buffer". Without removing it the tab bar would vanish
  ;; the instant the new tab opens, leaving no visible way back to the other
  ;; tabs -- self-defeating for a button whose whole job is opening a tab.
  ;;
  ;; The module adds the same function to `+doom-dashboard-mode-hook' too,
  ;; but nothing in Doom runs that deprecated name any more, so removing it
  ;; from `+dashboard-mode-hook' alone is sufficient.
  (remove-hook '+dashboard-mode-hook #'+tabs-disable-centaur-tabs-mode-maybe-h))

;; centaur-tabs ships no keybindings of its own; Doom's `:ui tabs' module only
;; adds `gt'/`gT' (`+tabs:next-or-goto', which take a count -- `4gt' jumps to
;; the 4th visible tab). These fill in the operations that otherwise need M-x.
;;
;; `ga' deliberately shadows evil's `what-cursor-position' -- that command is
;; a debugging curiosity, tab-jumping is a per-minute operation. `M-x
;; what-cursor-position' and `C-x =' both still reach it.
;;
;; New-tab lives under `SPC b' rather than `SPC t' (toggle): a centaur tab
;; *is* a buffer, so it belongs next to `SPC b N' (new empty buffer), and
;; opening a tab isn't a toggle.
(map! :after centaur-tabs
      :n "ga" #'centaur-tabs-ace-jump           ; C-u swaps, C-u C-u closes
      :n "g<" #'centaur-tabs-move-current-tab-to-left
      :n "g>" #'centaur-tabs-move-current-tab-to-right
      (:leader
       (:prefix "b"
        :desc "New tab (dashboard)"  "t" #'centaur-tabs--create-new-tab
        :desc "Switch tab group"     "T" #'centaur-tabs-switch-group
        :desc "Kill other tabs (group)" "o" #'centaur-tabs-kill-other-buffers-in-current-group)))

;; Leftover cosmetic-module commands with no key at all. Doom already covers
;; the rest: `SPC t z'/`t Z' (zen), `t m' (minimap), `t i' (indent-guides),
;; `t d' (vc-gutter) with `SPC g ]'/`g [' for hunks, `SPC o p'/`o P'
;; (treemacs), `SPC i e'/`i u' (emoji/unicode), `]t'/`[t' (hl-todo nav),
;; `SPC TAB ...' (workspaces), `SPC w 1'-`w 9' (window-select/winum), and
;; ``C-`'' (popup). Only these two were unreachable outside `M-x'.
;;
;; `SPC o h' -- the dashboard is a buffer you can only get back to by killing
;; everything else; `+dashboard/open' is its front door. `h' for "home",
;; matching the fallback buffer's role.
;;
;; `SPC s h' -- `hl-todo' highlights TODO/FIXME/HACK everywhere but only ships
;; point-to-point motion; `hl-todo-occur' is the list view. It sits under
;; search rather than toggle because it answers "where are they", not
;; "show/hide them".
(map! :leader
      :desc "Dashboard (home)" "o h" #'+dashboard/open
      :desc "TODOs in buffer"  "s h" #'hl-todo-occur)

;; `:ui treemacs' and `:emacs dired +dirvish' both bind `SPC o p' to "Project
;; sidebar"; treemacs' binding is declared later in Doom's `+evil-bindings.el',
;; so it wins and `dirvish-side' becomes reachable only from `M-x'. Rather than
;; drop a module, both are kept and split by axis -- the same per-axis reading
;; of the one-tool-per-responsibility rule that ADR-021 applied to Corfu and
;; Vertico. Treemacs is structural browsing (and carries the `+lsp' symbol,
;; error, and call-hierarchy trees on `SPC c S'/`c X'/`c y'); dirvish-side is
;; file manipulation -- rename, chmod, wdired -- in a narrow window.
;; Full dirvish stays on `SPC o /'.
(map! :leader :desc "Project sidebar (dirvish)" "o s" #'dirvish-side)

;; Save minibuffer history (Vertico likes this)
(after! savehist
  (savehist-mode 1))

;; Preview results as you move (feel free to set to nil if annoying)
(after! consult
  (setq consult-preview-key "M-."))

(map! :leader
      :desc "Search project (ripgrep)" "s p" #'consult-ripgrep)

(after! projectile
  (setq projectile-project-search-path '("~/Documents/")
        projectile-indexing-method 'alien) ; uses external tools (fast)
  ;; Was two `after! projectile' blocks, the second a superset of the first
  ;; (it added "venv" and ".pytest_cache"). Merged in Phase 7.
  (dolist (dir '(".venv" "venv" "__pycache__" ".mypy_cache" ".pytest_cache" ".ruff_cache"))
    (add-to-list 'projectile-globally-ignored-directories dir)))

;; No Magit keybinding here on purpose. Doom's `:config default +bindings'
;; already binds roughly thirty-five keys under `SPC g' -- status at `SPC g g',
;; the forge dispatch at `SPC g '', git-timemachine at `SPC g t', git-link at
;; `SPC g y', and issue/PR find-browse-list submaps under `f'/`o'/`l'. This repo
;; previously added `SPC g s' -> `magit-status', which did two unhelpful things:
;; it duplicated `SPC g g', and because `config.el' loads after all modules it
;; *overwrote* Doom's `SPC g s' -> `+vc-gutter/stage-hunk'. Measured in a
;; headless daemon before removal: `(lookup-key doom-leader-map (kbd "g s"))'
;; and `(kbd "g g")' both returned `magit-status'. Same shadowing mechanism as
;; ADR-028's `SPC o l' collision, on a smaller scale.
;;
;; `gptel-magit' needs nothing here either: `:tools llm' installs it via
;; `:hook (magit-mode . gptel-magit-install)', which binds `M-g' in the commit
;; buffer and adds "Generate commit" to the `magit-commit' transient.

;; `my/project-ghostel' lived here from the vterm era (ADR-014) purely because
;; vterm shipped no project-root-scoped entry point of its own. Ghostel does:
;; `ghostel-project' resolves the root, reuses an existing terminal for the
;; project instead of spawning duplicates, prefixes the buffer with the project
;; name, distinguishes local from TRAMP projects of the same name, and passes
;; the prefix argument through. All of that was missing from the hand-rolled
;; version, so the custom defun is deleted rather than kept alongside.
(map! :leader :desc "Project ghostel" "p t" #'ghostel-project)

;; Make it reachable from `project-switch-project' too, as upstream documents.
(after! project
  (add-to-list 'project-switch-commands '(ghostel-project "Ghostel") t))

;; The native module lives outside straight's build tree deliberately. Left at
;; its default, `ghostel-module-directory' resolves to the package directory --
;; which straight version-stamps (`straight/build-31.1/'), so the Emacs 30.2 ->
;; 31.1 upgrade on 2026-08-26 orphaned the downloaded .so in `build-30.2/' and
;; left every terminal path dead until it was fetched again. Upstream's own
;; docstring recommends a path outside the package manager's tree for exactly
;; this reason. `doom-data-dir' over `doom-cache-dir' because a cache clear
;; should not cost a redownload, and over `~/.config/emacs/' because that is
;; Doom's own git checkout (same reasoning as `oauth2-auto-plstore' in ADR-025).
;; Set at top level, not in `after! ghostel': ghostel.el calls
;; `ghostel--load-module' as it loads, so an `after!' would run too late.
(setq ghostel-module-directory (expand-file-name "ghostel/" doom-data-dir))

;; Terminal output from long agent sessions (claude-code-ide drives its CLI
;; through this backend) blows past the 5MB upstream default -- 5MB is roughly
;; 5,000 rows at 80 columns, fewer as the window widens. 20MB buys ~4x that.
;; Cost is per live ghostel buffer, so this is a deliberate memory-for-history
;; trade, not a free win; drop it back if several terminals are open at once.
(after! ghostel
  (setq ghostel-max-scrollback (* 20 1024 1024)
        ;; Bold text keeps the normal foreground upstream, which flattens TUI
        ;; output that leans on bold for emphasis. `bright' maps ANSI 0-7 to
        ;; 8-15, so bold picks up zenburn's bright variants.
        ghostel-bold-color 'bright
        ;; Lets programs in the terminal write the kill ring and system
        ;; clipboard via OSC 52 -- the point is copying out of a TUI (tmux,
        ;; nvim) over SSH. Upstream defaults this off because it means any
        ;; process in the terminal can overwrite the clipboard; enabled here
        ;; deliberately, revert to nil if that ever bites.
        ghostel-enable-osc52 t)

  ;; Shell integration can call whitelisted Emacs commands (the OSC 52 ";e"
  ;; subcommand, so this rides on `ghostel-enable-osc52' above). Point being:
  ;; `find-file' from inside the terminal reuses THIS Emacs instead of nesting
  ;; a second one. Only add commands that are harmless to invoke with arbitrary
  ;; string arguments -- terminal output is untrusted input to this whitelist.
  (add-to-list 'ghostel-eval-cmds '("magit-status" magit-status) t)

  ;; A command that finishes while the terminal is off-screen otherwise
  ;; announces itself nowhere. The hook fires synchronously from the parser, so
  ;; per upstream's docstring the actual work is deferred off the parser.
  (add-hook 'ghostel-command-finish-functions
            (defun +ghostel-notify-finished-h (buffer status)
              (unless (eq buffer (window-buffer (selected-window)))
                (run-at-time
                 0 nil
                 (lambda ()
                   (when (buffer-live-p buffer)
                     (message "%s: command finished (exit %s)"
                              (buffer-name buffer) (or status "?"))))))))

  ;; Live terminals keep the palette they were created with, so a theme switch
  ;; leaves them stale until the palette is re-pushed. Inside `after!' because
  ;; `doom-load-theme-hook' fires during startup, before ghostel is loaded.
  (add-hook 'doom-load-theme-hook #'ghostel-sync-theme))

;; Shell integration tracks every prompt (OSC 133), but nothing was bound to
;; move between them. Hyperlink motion covers the links `ghostel-enable-url-
;; detection' and `-enable-file-detection' are already generating.
(map! :map ghostel-mode-map
      "C-c C-p" #'ghostel-previous-prompt
      "C-c C-n" #'ghostel-next-prompt
      "C-c C-f" #'ghostel-next-hyperlink
      "C-c C-b" #'ghostel-previous-hyperlink
      "C-c C-l" #'ghostel-clear-scrollback
      ;; Line mode edits the pending shell line as an ordinary Emacs buffer,
      ;; with `completion-at-point' -- i.e. Corfu/Vertico instead of readline.
      ;; Bound rather than made the default (`ghostel-initial-input-mode') until
      ;; it's had real use; flip that variable if it earns it.
      "C-c C-e" #'ghostel-line-mode)

;; Terminal rows sit tighter than Doom's default text; a little leading makes
;; dense output legible without costing a visible amount of height.
(setq-hook! 'ghostel-mode-hook line-spacing 0.1)

;; Emojify replaces emoji characters with images, which breaks terminal column
;; alignment (an image is one glyph wide where the emulator laid out two) and
;; churns on high-volume output. Terminal output renders as the shell sent it.
(after! emojify
  (add-to-list 'emojify-inhibit-major-modes 'ghostel-mode))

;; No popup rule existed, so `SPC p t' reused whatever window it landed in.
;; :quit nil and :ttl nil keep a live shell from being closed by `C-g' or
;; reaped while idle -- a terminal holding a running process is not a
;; transient buffer.
(set-popup-rule! "^\\*ghostel" :size 0.35 :vslot -4 :select t :quit nil :ttl nil)

;; The `:term ghostel' module already inherits `ghostel-default' from
;; `solaire-default-face' (#303030), so terminals are dimmer than file buffers
;; (#3F3F3F) out of the box -- but so is every other solaire buffer (treemacs,
;; dirvish-side, dashboard), which makes the terminal indistinguishable from
;; the furniture around it. An explicit background one step darker still
;; (zenburn bg-1) separates it from both. This overrides only the background
;; attribute, so the module's solaire hook keeps managing `:inherit'.
(custom-set-faces!
  '(ghostel-default :background "#2B2B2B" :height 0.95))

;; vterm didn't repaint reliably when its window was resized while it wasn't
;; the selected window (a known vterm/libvterm bug class). This was worked
;; around here via a window-size-fixed freeze on vterm-mode-hook (added
;; 2026-08-07, removed 2026-08-17 when vterm itself was migrated away from —
;; see ADR-014). Not carried over to ghostel: no equivalent corruption has
;; been observed, and claude-code-ide.el already actively re-syncs ghostel's
;; process window size on resize (see claude-code-ide.el's
;; ghostel--window-adjust-process-window-size call), which vterm never had.
;; If the same visual-corruption symptom ever recurs under ghostel, revisit
;; with an equivalent freeze scoped to ghostel-mode-hook instead.

(after! envrc
  (envrc-global-mode))

;; Python IDE Setup
(after! flycheck
  (flycheck-define-checker python-ruff
    "A Python linter using Ruff."
    :command ("ruff" "check"
              "--output-format" "concise"
              "--stdin-filename" source-original
              "-")
    :standard-input t
    :error-patterns
    ((error line-start (file-name) ":" line ":" column ": " (message) line-end))
    :modes (python-mode python-ts-mode))

  (add-to-list 'flycheck-checkers 'python-ruff))

(after! (flycheck lsp-mode)
  (defun my/python-flycheck-chain-lsp-then-ruff ()
    "In Python buffers, run LSP diagnostics first, then Ruff."
    (when (and (memq major-mode '(python-mode python-ts-mode))
               (bound-and-true-p lsp-mode)
               (flycheck-valid-checker-p 'lsp)
               (flycheck-valid-checker-p 'python-ruff))
      (setq-local flycheck-checker 'lsp)
      (flycheck-remove-next-checker 'lsp 'python-ruff)
      (flycheck-add-next-checker 'lsp 'python-ruff 'append)))

  (add-hook 'lsp-managed-mode-hook #'my/python-flycheck-chain-lsp-then-ruff))


(after! python
  ;; Use Black as the formatter for Python (file-based, respects pyproject.toml)
  (set-formatter! 'black '("black" "-q" "--stdin-filename" (or buffer-file-name "stdin.py") "-"))
  (setq-hook! 'python-mode +format-with 'black)
  (setq-hook! 'python-ts-mode +format-with 'black))

(defun my/python-ruff-fix-buffer ()
  "Run `ruff check --fix` on a temp file, then replace the buffer with the fixed code.
Does not write to disk unless you save."
  (interactive)
  (unless (executable-find "ruff")
    (user-error "Ruff not found on PATH"))
  (unless buffer-file-name
    (user-error "Save the file once so Ruff can resolve project settings"))

  (let* ((root (or (locate-dominating-file default-directory "pyproject.toml")
                   default-directory))
         (tmp  (make-temp-file (expand-file-name "ruff-fix-" root) nil ".py"))
         (orig (buffer-string))
         (orig-point (point)))
    (unwind-protect
        (progn
          ;; write buffer to temp file
          (with-temp-file tmp
            (insert orig))

          ;; run ruff fix on temp file; ignore exit code
          (call-process "ruff" nil "*ruff-fix*" nil
                        "check" "--fix" tmp)

          ;; read fixed temp file back into buffer
          (let ((fixed (with-temp-buffer
                         (insert-file-contents tmp)
                         (buffer-string))))
            (if (string= orig fixed)
                (message "Ruff: no changes")
              (erase-buffer)
              (insert fixed)
              (goto-char (min orig-point (point-max)))
              (message "Ruff: fixes applied to buffer (not saved)"))))
      (when (file-exists-p tmp)
        (delete-file tmp)))))

(map! :after python
      :map (python-mode-map python-ts-mode-map)
      :localleader
      "r f" #'my/python-ruff-fix-buffer)

(after! lsp-pyright
  (setq lsp-pyright-typechecking-mode "strict"))

;; Add jk as an escape sequence
(after! evil-escape
  (setq evil-escape-key-sequence "jk"
        evil-escape-delay 0.20)
  (evil-escape-mode 1))

;; `:checkers grammar' ships two halves. `writegood-mode' is already live -- the
;; module hooks it into org/markdown/rst/latex and puts `g' and `r' on the
;; localleader. `langtool' is the other half, and it needs a LanguageTool
;; install to point at.
;;
;; The install here is the snap (`languagetool' 6.7, publisher vasilisc), and
;; the module's autodetection picks the wrong thing from it: it runs
;; `(executable-find "languagetool")', which finds /snap/bin/languagetool, a
;; wrapper whose run.sh hardcodes `java -jar languagetool.jar' -- the *GUI*. It
;; ignores every argument langtool.el passes it. A snap wrapper could not serve
;; anyway: langtool.el hands LanguageTool a temp file under /tmp for any
;; modified buffer, and a strictly-confined snap gets a private /tmp.
;;
;; The snap does ship the real commandline jar, so point langtool at that and
;; let the system JRE run it -- /snap is world-readable and the jar's relative
;; Class-Path resolves inside the snap. Verified 2026-08-30:
;; `java -jar <jar> -c utf8 -l en-US FILE' returns normal LanguageTool output.
;;
;; Setting this at top level rather than in an `after!' is what suppresses the
;; bad autodetect: the module's cond is guarded by `unless langtool-bin
;; langtool-language-tool-jar langtool-java-classpath', config.el loads before
;; langtool does, so a value set here is already in place when that cond runs.
(let ((jar "/snap/languagetool/current/usr/bin/languagetool-commandline.jar"))
  (when (file-readable-p jar)
    (setq langtool-language-tool-jar jar)))

;; AI: chat and focused transformation via gptel.
;; `:tools llm' owns gptel itself -- its package pin, `gptel-default-mode',
;; `gptel-display-buffer-action' and popup rule, the `SPC o l' keybinds, plus
;; gptel-magit/gptel-quick/ob-gptel. Only backend credentials and directives
;; live here; don't restate module defaults.
;; Credentials come from Doom's `:tools pass' module (`+auth' flag), never
;; hand-rolled shell wrappers. See docs/ai/providers.org for the full
;; credential map and docs/decisions.org ADR-003/004 for why the leader
;; namespace and provider choices look like this.
(after! gptel
  ;; Anthropic is the default backend. `:models' is deliberately omitted on
  ;; both backends below -- gptel ships and maintains its own current model
  ;; registry (gptel--anthropic-models / gptel--openai-models), so omitting
  ;; `:models' tracks upstream automatically instead of hardcoding names that
  ;; will be stale within months.
  (setq-default
   gptel-backend (gptel-make-anthropic "Claude"
                   :key (lambda () (+pass-get-secret "api/anthropic"))
                   :stream t)
   gptel-model 'claude-sonnet-5)

  ;; OpenAI kept as a secondary backend, explicitly selectable via `gptel-menu'.
  (gptel-make-openai "ChatGPT"
    :key (lambda () (+pass-get-secret "api/openai"))
    :stream t)

  ;; Reusable rewrite/transform directives, selectable from `gptel-rewrite''s
  ;; own transient (its "s" suffix edits/picks the active directive) instead
  ;; of bespoke commands that paste results into a scratch buffer for manual
  ;; copy-paste.
  (setf (alist-get 'clearer gptel-directives)
        "Make the following clearer and more concise while keeping the meaning. Return only the rewritten text.")
  (setf (alist-get 'formal gptel-directives)
        "Rewrite the following in a more formal tone. Return only the rewritten text.")
  (setf (alist-get 'summarize gptel-directives)
        "Summarize the following in 3-5 bullet points."))

(defun my/gptel-add-diagnostics ()
  "Add the current buffer's Flycheck diagnostics to gptel's context.
gptel has no built-in equivalent -- `gptel-add'/`gptel-add-file' cover
region/buffer/project-file context already."
  (interactive)
  (unless (bound-and-true-p flycheck-mode)
    (user-error "Flycheck is not active in this buffer"))
  (require 'flycheck)
  (let ((errors (flycheck-overlay-errors-in (point-min) (point-max)))
        (src (or (buffer-file-name) (buffer-name)))
        (buf (get-buffer-create "*gptel-diagnostics-context*")))
    (unless errors
      (user-error "No Flycheck diagnostics in this buffer"))
    (with-current-buffer buf
      (erase-buffer)
      (insert (format "Flycheck diagnostics for %s:\n\n" src))
      (dolist (err errors)
        (insert (format "%s:%s: %s: %s\n"
                        src
                        (flycheck-error-line err)
                        (flycheck-error-level err)
                        (flycheck-error-message err)))))
    (gptel-context--add-buffer buf)
    (message "Added %d diagnostic(s) to gptel context." (length errors))))

;; AI keys live in `:tools llm''s own `SPC o l' prefix (bound by :config
;; default +bindings, which covers gptel/gptel-send/gptel-add/gptel-add-file/
;; gptel-quick/gptel-rewrite/gptel-menu/gptel-org-set-topic+properties).
;; Only the two commands that map has no equivalent for are added, into the
;; same prefix -- the former `SPC a' namespace and its `embark-act' unbind
;; are gone. See docs/decisions.org ADR-028 (supersedes ADR-003).
;; The project terminal is unaffected: still `SPC p t' (see above).
(map! :leader
      :desc "Add diagnostics to context" "o l d" #'my/gptel-add-diagnostics
      :desc "Agent (Claude Code)"        "o l g" #'claude-code-ide-menu)

;; Credential store guard. On 2026-08-30 this host was found to have no
;; `pass' store at all, so gptel's Anthropic and OpenAI backends had been
;; dead here for an unknown length of time -- masked because
;; claude-code-ide authenticates through the Claude CLI's own login and
;; never touches `pass'. It was first read as state that had vanished; the
;; truth is that James set the store up on his laptop and this desktop
;; never had it (docs/inventory.org::inv-homedir-state-loss has the
;; measurements). Either way nothing announced the broken path, which is
;; what this guard fixes. ADR-035's answer -- tangle it from here -- cannot
;; apply: these must never be committed. So this is the detection half; the
;; recovery half is `~/.local/bin/pass-backup' (see the Shell layer), which
;; doubles as the transport for the pending laptop-to-desktop transfer.
;;
;; Entry *files* are checked, not decrypted: calling `+pass-get-secret' here
;; would fire a pinentry passphrase prompt on every startup, which is a much
;; worse daily cost than the failure it guards against.
;; ponytail: existence check only -- a present-but-corrupt entry still slips
;; through. Decrypt-on-demand if that ever actually happens.
(defvar my/pass-expected-entries
  '("api/anthropic" "api/openai" "mail/oauth2-google-client")
  "Entries `config.org' reads at runtime, checked for existence at startup.
See docs/ai/providers.org for what consumes each one.")

(defun my/pass-check-store ()
  "Warn if the `pass' store or any expected entry is missing.
Checks for the encrypted files only -- never decrypts, so it cannot
prompt for a passphrase."
  (let* ((dir (or (getenv "PASSWORD_STORE_DIR")
                  (expand-file-name "~/.password-store")))
         (missing (unless (file-directory-p dir)
                    (list dir))))
    (unless missing
      (setq missing
            (seq-remove (lambda (e)
                          (file-exists-p (expand-file-name (concat e ".gpg") dir)))
                        my/pass-expected-entries)))
    (when missing
      (delay-warning 'pass
                     (format "pass store incomplete -- missing: %s.
See PROJECT.org 7.7 and docs/ai/providers.org."
                             (string-join missing ", "))
                     :warning))))

(add-hook 'emacs-startup-hook #'my/pass-check-store)

;; Email: mu4e (+org +gmail +mbsync). Sync via mbsync (isync), send via
;; msmtp. Credentials never live here: the plain-password account resolves
;; via `pass show mail/<label>`, the two Google-backed accounts (one
;; consumer Gmail, one UAlberta Google Workspace) via `oama access <address>`
;; (oama manages the XOAUTH2 refresh cycle pass alone can't do).
;; See docs/decisions.org for the Email ADR and docs/ai/providers.org-style
;; credential map, and ~/.mbsyncrc / ~/.msmtprc for the actual PassCmd /
;; passwordeval wiring (outside the repo, chmod 600).
;; The leader binding is Doom's own default: `SPC o m' / `=mu4e', `SPC o M c'
;; to compose -- no custom map! needed here.
(with-eval-after-load 'mu4e
  (setq sendmail-program (executable-find "msmtp")
        send-mail-function #'smtpmail-send-it
        message-sendmail-f-is-evil t
        message-sendmail-extra-arguments '("--read-envelope-from")
        message-send-mail-function #'message-send-mail-with-sendmail
        ;; Neither personal's nor ualberta's maildir root is literally named
        ;; "gmail" (they're named by account label, not provider), so
        ;; `+mu4e-msg-gmail-p's `(string-match-p "gmail" root-maildir)'
        ;; fallback never catches either one -- both need to be listed here
        ;; explicitly to get the Gmail IMAP integrations (X-GM-LABELS
        ;; retagging for trash/refile/flag, auto-expunge handling). The cdr
        ;; must be the *root maildir* with no leading slash -- what
        ;; `+mu4e-msg-gmail-p' actually computes and compares against.
        ;; Previously only ualberta was listed, and with a leading slash
        ;; ("/ualberta") that never matched the slash-less comparison, so
        ;; this silently never worked for either account; see
        ;; docs/ai/troubleshooting.org::tshoot-mu4e-gmail-p-slash-mismatch.
        +mu4e-gmail-accounts '(("mrniceguyjames@gmail.com" . "personal")
                                ("jcook@ualberta.ca" . "ualberta"))
        ;; Background fetch; per-account maildirs are under ~/.mail/<label>/.
        mu4e-update-interval 60)

  ;; Spam: Gmail already filters spam server-side into "[Gmail]/Spam", and
  ;; mbsync mirrors it locally (Patterns * in ~/.mbsyncrc), so there's
  ;; nothing to "create" there for the personal/ualberta accounts -- just
  ;; give mu4e a way to *use* it, by physically moving the message into it
  ;; over IMAP. Gmail treats a move into "[Gmail]/Spam" as a spam report
  ;; and trains its filter from it, the same way moving into Trash/All Mail
  ;; already works for the built-in trash/refile marks -- deliberately NOT
  ;; using the doom+ mu4e module's X-GM-LABELS retag path (`+mu4e-msg-gmail-p'
  ;; + `+mu4e-gmail-fix-flags-h', fixed above for trash/refile/flag): a spam
  ;; report is exactly the kind of thing a real-mailbox move already handles
  ;; correctly, no retagging needed. tricca (plain IMAP via Gandi, not
  ;; Gmail) has no folder wired up: that account has never synced yet and
  ;; its server-side folder layout (if any spam/junk folder exists at all)
  ;; is unverified.
  ;;
  ;; `s' marks a message as spam, following the same pattern doom+'s mu4e
  ;; module already uses for refile (see its config.el): a plain
  ;; `mu4e--server-move' clearing the New flag.
  (defconst +mu4e-spam-accounts '("personal" "ualberta")
    "Root maildirs with a Gmail-style Spam folder wired up for the `spam' mu4e mark.")

  (defun +mu4e-get-spam-folder (msg)
    "Resolve MSG's account's Gmail Spam folder, e.g. \"/personal/[Gmail]/Spam\".
Errors for any account not listed in `+mu4e-spam-accounts'."
    (let ((root (replace-regexp-in-string
                 "/.*" "" (substring (mu4e-message-field msg :maildir) 1))))
      (if (member root +mu4e-spam-accounts)
          (concat "/" root "/[Gmail]/Spam")
        (mu4e-error "No spam folder configured for the %s account" root))))

  (setf (alist-get 'spam mu4e-marks)
        (list :char '("s" . "☠")
              :prompt "sspam"
              :dyn-target (lambda (_target msg) (+mu4e-get-spam-folder msg))
              :action (lambda (docid _msg target)
                        (mu4e--server-move docid (mu4e--mark-check-target target) "-N"))))

  ;; The stock "Unread messages" bookmark (`u') searches every maildir, so
  ;; unread mail Gmail already filed as spam would otherwise surface right
  ;; next to real unread mail. `maildir:/Spam/' matches any maildir ending
  ;; in "Spam" (see mu-query(7) MAILDIR), which covers both Gmail accounts'
  ;; "[Gmail]/Spam" in one clause.
  (when-let* ((bm (seq-find (lambda (bm) (equal (plist-get bm :name) "Unread messages"))
                             mu4e-bookmarks)))
    (plist-put bm :query "flag:unread AND NOT flag:trashed AND NOT maildir:/Spam/")))

(set-email-account! "personal"
  '((mu4e-sent-folder    . "/personal/[Gmail]/Sent Mail")
    (mu4e-drafts-folder  . "/personal/[Gmail]/Drafts")
    (mu4e-trash-folder   . "/personal/[Gmail]/Trash")
    (mu4e-refile-folder  . "/personal/[Gmail]/All Mail")
    (smtpmail-smtp-user  . "mrniceguyjames@gmail.com")
    (user-mail-address   . "mrniceguyjames@gmail.com")
    (smtpmail-smtp-server . "smtp.gmail.com"))
  t) ;; default account -- confirm this is the intended default

(set-email-account! "ualberta"
  '((mu4e-sent-folder    . "/ualberta/[Gmail]/Sent Mail")
    (mu4e-drafts-folder  . "/ualberta/[Gmail]/Drafts")
    (mu4e-trash-folder   . "/ualberta/[Gmail]/Trash")
    (mu4e-refile-folder  . "/ualberta/[Gmail]/All Mail")
    (smtpmail-smtp-user  . "jcook@ualberta.ca")
    (user-mail-address   . "jcook@ualberta.ca")
    (smtpmail-smtp-server . "smtp.gmail.com")))

(set-email-account! "tricca"
  '((mu4e-sent-folder    . "/tricca/Sent")
    (mu4e-drafts-folder  . "/tricca/Drafts")
    (mu4e-trash-folder   . "/tricca/Trash")
    (mu4e-refile-folder  . "/tricca/Archive")
    (smtpmail-smtp-user  . "jcook@tricca.ca")
    (user-mail-address   . "jcook@tricca.ca")
    (smtpmail-smtp-server . "mail.gandi.net")
    (smtpmail-smtp-service . 465)
    (smtpmail-stream-type  . ssl)))

;; RSS: elfeed (+org +youtube). Feeds are managed as an Org outline at
;; org-directory/elfeed.org (elfeed-org), not as a `elfeed-feeds' list here --
;; see that file for actual subscriptions. `+youtube' adds elfeed-tube, which
;; gives transcript fetching (`F' in the search and show buffers). See
;; docs/decisions.org for the RSS integration ADR.
(map! :leader :desc "RSS (elfeed)" "o r" #'elfeed)

;; The mpv half of elfeed-tube, declared in the packages section above. Doom's
;; module binds `C-c C-f' and `C-c C-w' to `elfeed-tube-mpv-follow-mode' and
;; `elfeed-tube-mpv-where' but never declares the package they come from, so
;; both keys were `void-function'.
;;
;; `:after elfeed-tube' rather than relying on autoloads, because only two of
;; the three commands carry an autoload cookie -- `elfeed-tube-mpv-where'
;; (elfeed-tube-mpv.el:260) has none, and `map!' does not force a load. Loading
;; alongside elfeed-tube defines all three, and elfeed-tube is itself deferred
;; behind elfeed, so this costs nothing until `SPC o r'.
(use-package! elfeed-tube-mpv
  :after elfeed-tube)

;; Auto-refresh feeds whenever the elfeed search buffer is opened, so `SPC o r'
;; doesn't show a buffer that's stale since the last manual `elfeed-update'.
(add-hook 'elfeed-search-mode-hook #'elfeed-update)

;; Torrents: transmission.el drives a local transmission-daemon over its RPC
;; API (see docs/decisions.org ADR-030). The daemon runs as a *user* systemd
;; unit (~/.config/systemd/user/transmission-daemon.service), not the packaged
;; system unit: that one ships `Type=notify' and times out on this Ubuntu, and
;; running as `debian-transmission' would leave every download owned by another
;; user. RPC listens on 127.0.0.1:9091 with authentication off, which is why no
;; credential lookup appears here -- if auth is ever turned on, the password
;; comes from auth-source (`:tools pass'), never a literal in this file.
;; `SPC o t'/`SPC o T' are ghostel's, so torrents take `SPC o B' (BitTorrent).
(map! :leader :desc "Torrents (transmission)" "o B" #'transmission)

(after! transmission
  ;; Poll the daemon while these buffers are visible, so the list isn't stale
  ;; between manual `g' presses. transmission.el's own documented opt-in --
  ;; it refreshes in these modes only.
  (setq transmission-refresh-modes '(transmission-mode
                                     transmission-files-mode
                                     transmission-info-mode
                                     transmission-peers-mode)))

;; Hand `magnet:' links to the daemon rather than the default browser, so a
;; magnet from eww, elfeed, or anywhere else that routes through `browse-url'
;; is added without a detour through a GUI client.
(add-to-list 'browse-url-handlers
             (cons "\\`magnet:"
                   (lambda (url &optional _new-window)
                     (transmission-add url))))

;; --- EPUB reading (docs/decisions.org ADR-034) -----------------------------
;; nov.el renders EPUB through `shr'. Nothing else is configured here on
;; purpose: Evil bindings come from evil-collection (`:editor evil
;; +everywhere' is on, and it ships a `nov' module), the reading position
;; comes from Doom's global `save-place-mode', and browsing a library of
;; files is what Dired/dirvish (`SPC o /', `SPC o s') already does.
(use-package! nov
  :mode ("\\.epub\\'" . nov-mode)
  :config
  ;; `perfect-margin' already owns the text column; nov's own hard fill
  ;; would wrap a second time inside those margins.
  (setq nov-text-width t))

;; App launcher: SPC o L -- raise-or-launch external GUI apps, plus a couple
;; of "the Emacs command *is* the app" bindings (calc, proced) that need no
;; process launching at all. This is a plain process launcher, not a window-
;; manager change -- EXWM itself stays deferred to its own future roadmap
;; phase per ADR-002 (docs/decisions.org). PDFs and images get no binding
;; here: both already auto-open via `find-file'/Dired -- PDFs through the
;; `pdf' module's pdf-tools (once its `epdfinfo' helper has `libpoppler-
;; glib-dev' to compile against), images through the built-in `image-mode'.
(defun my/launch-or-focus (app)
  "Focus a running window for APP, or launch APP as a new process.
APP is used both as the shell command to run and as the (best-effort,
substring) WM_CLASS pattern passed to `xdotool' when looking for an
already-running instance to focus instead of spawning a duplicate. Falls
back to always launching a fresh process if `xdotool' isn't on PATH, or no
matching window is found."
  (interactive)
  (let ((win (and (executable-find "xdotool")
                   (ignore-errors
                     (car (process-lines "xdotool" "search" "--class" app))))))
    (if win
        (call-process "xdotool" nil nil nil "windowactivate" win)
      (start-process app nil app))))

;; Moved off `SPC o l' 2026-08-23: that prefix belongs to `:tools llm' since
;; the module was enabled, and this `:prefix' form was silently replacing the
;; module's whole gptel map (see docs/decisions.org ADR-028).
(map! :leader
      (:prefix ("o L" . "launch")
       :desc "Firefox"                  "f" (cmd! (my/launch-or-focus "firefox"))
       :desc "Discord"                  "d" (cmd! (my/launch-or-focus "discord"))
       :desc "VLC"                      "v" (cmd! (my/launch-or-focus "vlc"))
       :desc "Calculator (calc)"        "c" #'calc
       :desc "Process monitor (proced)" "t" #'proced))

;; Inline completion: Copilot overlay + Next Edit Suggestions.
;; TAB/C-TAB below are copilot.el's own default bindings (`copilot-completion-map'
;; and `copilot-nes-mode-map'), not re-bound here -- both are activated via
;; overlay-local/filtered keymaps that fall through to Corfu/indent/yasnippet
;; when no suggestion is pending (Corfu, not Company, since ADR-021). See
;; docs/ai/keybindings.org for the precedence analysis and docs/decisions.org
;; ADR-007/ADR-021.
(use-package! copilot
  :hook ((prog-mode . copilot-mode)
         (prog-mode . copilot-nes-mode)))

(after! copilot
  (set-face-attribute 'copilot-overlay-face nil
                      :foreground "#9FC59F"  ;; zenburn green+2, bright but still subtle
                      :background 'unspecified))

;; Primary agentic coding workflow: claude-code-ide.el drives the already-
;; installed Claude Code CLI over MCP. Ediff-based review matches this
;; config's existing incumbent (docs/decisions.org ADR-004). Terminal backend
;; migrated from vterm to ghostel 2026-08-17 (docs/decisions.org ADR-014) to
;; get around a vterm/libvterm resize-repaint bug; live-verified to
;; render/resize correctly before this flip, and again via a full from-scratch
;; smoke-test re-run. Vterm itself (module and all its call sites in this
;; config) was removed the same day once ghostel covered every prior use.
;; Settings below are set explicitly even where they match upstream defaults,
;; so an upstream default change doesn't silently change behavior here.
(use-package! claude-code-ide
  :commands (claude-code-ide-menu)
  :init
  (setq claude-code-ide-terminal-backend 'ghostel
        claude-code-ide-diagnostics-backend 'flycheck
        claude-code-ide-use-ide-diff t)
  :config
  (claude-code-ide-emacs-tools-setup))

;; Note management: Vulpea indexes any org entry (file- or heading-level)
;; carrying an `ID' property into its own sqlite database -- titles, tags,
;; id: links, and description-list metadata. Vulpea 2.x is standalone (its
;; Package-Requires names emacsql, not org-roam; v1 was the org-roam layer),
;; so it and org-roam are two independent databases, not a stack. Notes are
;; picked up from `org-directory' (set above) since
;; `vulpea-db-sync-directories' is left at its default. Deferred to first
;; input so it never blocks startup; `vulpea-db-autosync-mode' does the
;; initial database scan in the background and then watches for changes.
(use-package! vulpea
  :defer t :after-call doom-first-input-hook
  :config
  (vulpea-db-autosync-mode +1))

;; org-roam runs alongside Vulpea (docs/decisions.org ADR-027), with Vulpea
;; winning every overlap. Three settings hold that line; each corresponds to
;; a place the two packages would otherwise both answer the same question:
;;
;; 1. Scope. `org-roam-directory' stays at Doom's default (~/org/roam/),
;;    NOT `org-directory'. Vulpea owns the whole tree; org-roam owns one
;;    subdirectory inside it. This also keeps the two autosync watchers off
;;    each other's files for everything outside ~/org/roam/.
;; 2. In-buffer completion. Doom's org-roam config sets
;;    `org-roam-completion-everywhere' to t, which installs a
;;    completion-at-point that offers roam nodes while typing in any org
;;    buffer -- directly competing with `vulpea-insert'. Turned back off.
;; 3. Backlinks. `+org-roam-auto-backlinks-buffer' is nil by default, and is
;;    pinned here so an upstream default-flip can't start auto-opening
;;    org-roam's right-side buffer on top of `my/vulpea-buffer-toggle''s
;;    (both claim :side right; see the vulpea backlinks section below).
;;
;; org-roam's own commands stay reachable under Doom's stock `SPC n r'
;; prefix -- this makes Vulpea primary, it doesn't disable org-roam.
(after! org-roam
  (setq org-roam-completion-everywhere nil
        +org-roam-auto-backlinks-buffer nil))

;; Org Agenda & Capture basics (docs/decisions.org ADR-017). Deliberately
;; minimal per docs/standards.org std-no-scope-creep ("don't build the full
;; Org Agenda system until its own phase") -- this *is* that phase, scoped to
;; agenda-files/TODO-states/capture-templates only, no custom agenda views.
;; `org-agenda-files' covers the whole pre-existing `org-directory' tree
;; (~/org/), including files that predate this project (e.g. `doom.org' has a
;; stray "TODO" headline that isn't really a task) -- a deliberate, informed
;; choice, not an oversight. TODO keywords match this repo's own PROJECT.org
;; convention rather than inventing a second one. Capture templates file into
;; the "Inbox" headline `~/org/todo.org' already had (pre-dating this
;; project); the third creates a real Vulpea-indexed note using the exact
;; org-capture target pattern Vulpea's own docs recommend (`vulpea-create' as
;; the file target, so the note gets an ID/backlinks like any
;; `vulpea-find'-created note would).
(after! org
  ;; `org-agenda-files' expands a *directory* entry non-recursively -- it picks
  ;; up that directory's own .org files and does not descend. The original
  ;; `(list org-directory)' therefore resolved to exactly two files,
  ;; ~/org/todo.org and ~/org/doom.org, while ADR-017 and the comment above both
  ;; describe it as covering "the whole pre-existing `org-directory' tree".
  ;; Measured in a headless daemon during Phase 7: `(org-agenda-files)' returned
  ;; those two paths out of 68 .org files in the tree -- work/ (15 files),
  ;; personal/ (3), calendar/ (2, org-gcal-owned), daily/, mtg/ and test/ were
  ;; all invisible to every agenda view. The calendar/ case also quietly
  ;; undercut ADR-025, which assumes synced Google events reach the agenda.
  ;;
  ;; Listing `org-directory' plus each of its immediate subdirectories gives the
  ;; documented behaviour. Depth-1 only, and evaluated at load: a *new*
  ;; subdirectory needs a reload to be picked up, which is the tradeoff for not
  ;; re-scanning the tree on every agenda build.
  (setq org-agenda-files
        (cons org-directory
              (seq-filter #'file-directory-p
                          (directory-files org-directory t "\\`[^.]")))
        org-todo-keywords
        '((sequence "TODO(t)" "IN-PROGRESS(i)" "BLOCKED(b)" "|" "DONE(d)" "REJECTED(r)"))
        org-capture-templates
        `(("t" "Task" entry
           (file+headline ,(expand-file-name "todo.org" org-directory) "Inbox")
           "* TODO %?\n%U" :empty-lines 1)
          ("n" "Note" entry
           (file+headline ,(expand-file-name "todo.org" org-directory) "Inbox")
           "* %?\n%U" :empty-lines 1)
          ("v" "Vulpea note" plain
           (file ,(lambda ()
                    (vulpea-note-path
                     (vulpea-create (read-string "Title: ")))))
           "%?"))))

(after! org
  (setq org-agenda-custom-commands
        `(("d" "Day — what is actually live"
           ((agenda "" ((org-agenda-span 1)
                        ;; Doom sets `org-agenda-start-day' to "-3d" globally, so
                        ;; a span-1 view that does not override it renders three
                        ;; days ago under the heading "Today". Caught in a daemon:
                        ;; the block was labelled Today and dated 27 August while
                        ;; the system clock said the 30th.
                        (org-agenda-start-day nil)
                        (org-agenda-overriding-header "Today")))
            (todo "IN-PROGRESS"
                  ((org-agenda-overriding-header "In progress")))
            (todo "BLOCKED"
                  ((org-agenda-overriding-header "Blocked — needs something")))
            (todo "TODO"
                  ((org-agenda-files
                    (list ,(expand-file-name "todo.org" org-directory)))
                   (org-agenda-overriding-header "Inbox")))))

          ("w" "Week ahead"
           ((agenda "" ((org-agenda-span 7)
                        (org-agenda-start-day nil) ; same -3d inheritance
                        (org-agenda-overriding-header "Next seven days")))))

          ("b" "Blocked — unblocking sweep"
           todo "BLOCKED"
           ((org-agenda-overriding-header "Everything blocked")))

          ("u" "Unfiled inbox"
           todo "TODO"
           ((org-agenda-files
             (list ,(expand-file-name "todo.org" org-directory)))
            (org-agenda-overriding-header "Inbox — file or schedule these")))

          ("s" "Stale — TODOs with no date attached"
           todo "TODO"
           ((org-agenda-skip-function
             '(org-agenda-skip-entry-if 'scheduled 'deadline))
            (org-agenda-overriding-header
             "Unscheduled TODOs (no scheduled date, no deadline)"))))))

;; Vulpea dailies (docs/decisions.org ADR-018): a hand-rolled equivalent of
;; org-roam-dailies -- Vulpea itself has no daily-note concept. Each day is
;; its own real Vulpea file-level note (ID, backlinks, findable via
;; `vulpea-find' like anything else) at org-directory/daily/YYYY-MM-DD.org,
;; created on first visit via `vulpea-create'.
(defun my/vulpea-daily--file (date)
  "Return the daily-note file path for DATE (a \"YYYY-MM-DD\" string)."
  (expand-file-name (format "daily/%s.org" date) org-directory))

(defun my/vulpea-daily--goto (date)
  "Visit the daily note for DATE, creating it via `vulpea-create' if needed."
  (let ((file (my/vulpea-daily--file date)))
    (unless (file-exists-p file)
      (vulpea-create date (format "daily/%s.org" date) :tags '("daily")))
    (find-file file)))

(defun my/vulpea-daily--dates ()
  "Return the existing daily-note dates, sorted chronologically."
  (let ((dir (expand-file-name "daily/" org-directory)))
    (when (file-directory-p dir)
      (sort (mapcar #'file-name-sans-extension
                     (directory-files dir nil "\\`[0-9]\\{4\\}-[0-9]\\{2\\}-[0-9]\\{2\\}\\.org\\'"))
            #'string<))))

(defun my/vulpea-daily--current-date ()
  "Return the date the current buffer's daily note is for, or nil."
  (when-let* ((file (buffer-file-name))
              (dir (expand-file-name "daily/" org-directory)))
    (when (string-prefix-p dir (expand-file-name file))
      (file-name-sans-extension (file-name-nondirectory file)))))

(defun my/vulpea-daily--adjacent (direction)
  "Visit the nearest existing daily note before/after the current one.
DIRECTION is `previous' or `next'."
  (let* ((dates (my/vulpea-daily--dates))
         (current (or (my/vulpea-daily--current-date)
                      (format-time-string "%Y-%m-%d")))
         (candidates (if (eq direction 'previous)
                         (reverse (seq-filter (lambda (d) (string< d current)) dates))
                       (seq-filter (lambda (d) (string> d current)) dates))))
    (if candidates
        (find-file (my/vulpea-daily--file (car candidates)))
      (message "No %s daily note" (if (eq direction 'previous) "earlier" "later")))))

(defun my/vulpea-daily-today ()
  "Open (creating if needed) today's daily note."
  (interactive)
  (my/vulpea-daily--goto (format-time-string "%Y-%m-%d")))

(defun my/vulpea-daily-date ()
  "Open (creating if needed) the daily note for a prompted date."
  (interactive)
  (my/vulpea-daily--goto (format-time-string "%Y-%m-%d" (org-read-date nil t))))

(defun my/vulpea-daily-previous ()
  "Visit the previous existing daily note."
  (interactive)
  (my/vulpea-daily--adjacent 'previous))

(defun my/vulpea-daily-next ()
  "Visit the next existing daily note."
  (interactive)
  (my/vulpea-daily--adjacent 'next))

;; Vulpea backlinks buffer (docs/decisions.org ADR-018): a hand-rolled,
;; deliberately scoped equivalent of org-roam-buffer -- Vulpea only ships
;; jump-to-backlink (`vulpea-find-backlink'), not a live panel. Shows the
;; current note's incoming links only (no unlinked-references section, no
;; citation backlinks). Refreshes on both a window-selection change (moving
;; to a different window) and a window-buffer change (visiting a different
;; note in the *same* window, e.g. via `vulpea-find' or `vulpea-find-backlink'
;; -- the more common case, and the reason both hooks are needed rather than
;; just one).
(defvar my/vulpea-buffer-name "*vulpea-buffer*")

(defvar-local my/vulpea-buffer--shown-id nil
  "ID of the note currently rendered in the Vulpea backlinks buffer.")

(define-derived-mode my/vulpea-buffer-mode special-mode "Vulpea-Backlinks"
  "Major mode for the hand-rolled Vulpea backlinks side buffer.")

(defun my/vulpea-buffer--note-for-window (window)
  "Return the Vulpea note backing WINDOW's buffer's file, or nil."
  (when-let* ((file (buffer-file-name (window-buffer window))))
    (car (vulpea-db-query-by-file-path file 0))))

(defun my/vulpea-buffer--render (note)
  "Render NOTE's backlinks into the Vulpea backlinks buffer."
  (with-current-buffer (get-buffer-create my/vulpea-buffer-name)
    (unless (derived-mode-p 'my/vulpea-buffer-mode)
      (my/vulpea-buffer-mode))
    (let* ((inhibit-read-only t)
           (links (vulpea-db-query-links-to (vulpea-note-id note)))
           (id->note (make-hash-table :test #'equal)))
      (when links
        (dolist (n (vulpea-db-query-by-ids
                    (delete-dups (mapcar (lambda (l) (plist-get l :source)) links))))
          (puthash (vulpea-note-id n) n id->note)))
      (erase-buffer)
      (insert (propertize (vulpea-note-title note) 'face 'org-document-title) "\n\n"
              (format "Backlinks (%d)\n" (length links))
              (make-string 20 ?-) "\n\n")
      (if (null links)
          (insert "No backlinks.\n")
        (dolist (link links)
          (when-let* ((src (gethash (plist-get link :source) id->note)))
            (insert-text-button (vulpea-note-title src)
                                 'action (lambda (_) (vulpea-visit src))
                                 'follow-link t)
            (when-let* ((desc (plist-get link :description)))
              (insert (format "  — %s" desc)))
            (insert "\n"))))
      (goto-char (point-min))
      (setq my/vulpea-buffer--shown-id (vulpea-note-id note)))))

(defun my/vulpea-buffer--maybe-update (&optional _frame)
  "Refresh the Vulpea backlinks buffer for the selected window, if visible."
  (when (get-buffer-window my/vulpea-buffer-name)
    (when-let* ((note (my/vulpea-buffer--note-for-window (selected-window))))
      (unless (equal (vulpea-note-id note)
                     (buffer-local-value 'my/vulpea-buffer--shown-id
                                         (get-buffer my/vulpea-buffer-name)))
        (my/vulpea-buffer--render note)))))

(defun my/vulpea-buffer-toggle ()
  "Toggle a live side window showing backlinks to the current buffer's note."
  (interactive)
  (if-let* ((win (get-buffer-window my/vulpea-buffer-name)))
      (delete-window win)
    (if-let* ((note (my/vulpea-buffer--note-for-window (selected-window))))
        (progn
          (display-buffer-in-side-window
           (get-buffer-create my/vulpea-buffer-name)
           '((side . right) (slot . 0) (window-width . 0.30)))
          (my/vulpea-buffer--render note))
      (message "Current buffer is not a Vulpea note"))))

(add-hook 'window-selection-change-functions #'my/vulpea-buffer--maybe-update)
(add-hook 'window-buffer-change-functions #'my/vulpea-buffer--maybe-update)

(map! :leader
      (:prefix ("n v" . "vulpea")
       :desc "Find note"     "f" #'vulpea-find
       :desc "Find backlink" "b" #'vulpea-find-backlink
       :desc "Insert link"   "i" #'vulpea-insert
       :desc "Full scan"     "s" #'vulpea-db-sync-full-scan
       :desc "Diagnostics"   "d" #'vulpea-doctor
       :desc "Toggle backlinks buffer" "B" #'my/vulpea-buffer-toggle
       :desc "Daily: today"     "j" #'my/vulpea-daily-today
       :desc "Daily: pick date" "J" #'my/vulpea-daily-date
       :desc "Daily: previous"  "p" #'my/vulpea-daily-previous
       :desc "Daily: next"      "n" #'my/vulpea-daily-next))

;; GTD extension (zettelkasten-integration plan, workstream 1). Appends to
;; ADR-017's `org-capture-templates'/`org-agenda-custom-commands' rather than
;; redefining them, so this block is additive regardless of file order
;; relative to the "Org Agenda and Capture basics" section above.
;;
;; Two new dedicated files -- ~/org/projects.org, ~/org/someday.org -- both
;; land at the top level of `org-directory'. `org-agenda-files' already
;; includes `org-directory' itself as a directory entry (see above), and Org
;; re-expands a directory entry to its current .org files on every agenda
;; build, not only at the load-time the list itself was computed -- so a new
;; *file* inside an already-listed directory needs no reload, unlike a new
;; *subdirectory* (which does, per the comment above). Neither file is
;; created by this config; org-capture's own `file' target semantics create
;; it on first use.
;;
;; No new "waiting" TODO state: `BLOCKED' already means exactly that ("needs
;; something [from someone/something] before it can move"), and the existing
;; "b" custom agenda view (tree-wide `todo "BLOCKED"') already sweeps every
;; BLOCKED entry regardless of which file it's filed in. Filing waiting-for
;; items as BLOCKED gets them a review view for free instead of inventing a
;; parallel keyword and a parallel view for the same concept.
(after! org
  (setq org-capture-templates
        (append
         org-capture-templates
         `(("p" "GTD project" entry
            (file ,(expand-file-name "projects.org" org-directory))
            ;; `:project:' is a structural/type tag ("this heading is a
            ;; project"), not a GTD context tag -- it exists only so a
            ;; project heading stays visually distinct from ordinary TODO
            ;; subtasks added under it by hand later. TODO keyword reused
            ;; unchanged from ADR-017's sequence: a project is itself
            ;; something to work, so it belongs in the same TODO searches as
            ;; any other task.
            "* TODO %? :project:\n%U" :empty-lines 1)
           ("s" "Someday/maybe" entry
            (file ,(expand-file-name "someday.org" org-directory))
            ;; Deliberately no TODO keyword. Giving these a keyword would
            ;; pull them into the tree-wide "TODO" searches ("u"/"s" above)
            ;; -- the entire point of a someday/maybe list is that it stays
            ;; inert until a human promotes an entry to a real task by hand
            ;; (at which point they'd add a keyword themselves).
            "* %?\n%U" :empty-lines 1)
           ("w" "Waiting for" entry
            (file+headline ,(expand-file-name "todo.org" org-directory) "Waiting")
            ;; `file+headline' creates the "Waiting" headline in todo.org on
            ;; first use if it isn't already there (stock org-capture
            ;; behaviour: missing headline -> created at end of file) -- no
            ;; separate waiting-for.org needed for this.
            "* BLOCKED %?\n%U" :empty-lines 1))))
  ;; One new review view: someday/maybe entries carry no TODO keyword (see
  ;; above), so they're invisible to every todo-keyword-based view including
  ;; "b"/"u"/"s" -- by design, but that means they also need their own way
  ;; back into view, or the list becomes write-only. `tags' with a bare
  ;; "LEVEL=1" match (a property match, not an actual tag) lists every
  ;; top-level heading in the file regardless of tags/keyword, scoped to
  ;; someday.org the same way "u"'s Inbox block scopes to todo.org.
  (setq org-agenda-custom-commands
        (append
         org-agenda-custom-commands
         `(("m" "Someday/maybe — review list"
            tags "LEVEL=1"
            ((org-agenda-files (list ,(expand-file-name "someday.org" org-directory)))
             (org-agenda-overriding-header "Someday / maybe")))))))

;; PARA scheme (zettelkasten-integration plan sec.4): a `PARA' org property
;; -- Project / Area / Resource / Archive -- layered on the existing flat
;; `org-directory' tree Vulpea already indexes whole. Not a folder taxonomy:
;; nothing here moves files or forces a re-scan. "Archiving" a note is just
;; flipping this property to "Archive"; `vulpea-db-autosync-mode''s
;; file-notify watcher (see the Note management: Vulpea section above) picks
;; up the save exactly like any other edit, so no explicit resync call is
;; made below. Property, not a tag, so it can be queried with Vulpea's own
;; `vulpea-db-query-by-property' (indexed lookup) rather than a tag scan.
(defconst my/vulpea-para-values '("Project" "Area" "Resource" "Archive")
  "The four PARA classification values, in Tiago Forte's canonical order.")

(defun my/vulpea-para--goto (note)
  "Move point in the current buffer to NOTE's entry.
NOTE must be backed by the current buffer's file. File-level notes
\(level 0) go to `point-min'; heading-level notes are found by their
`:ID:' property line -- the same lookup `vulpea-visit' itself does."
  (goto-char (point-min))
  (unless (= (vulpea-note-level note) 0)
    (unless (re-search-forward
             (format "^[ \t]*:ID:[ \t]+%s[ \t]*$" (regexp-quote (vulpea-note-id note)))
             nil t)
      (user-error "Could not find heading with ID: %s" (vulpea-note-id note)))
    (org-back-to-heading t)))

(defun my/vulpea-para--current-note ()
  "Return the Vulpea note backing the current buffer's file, or nil."
  (when-let* ((file (buffer-file-name)))
    (car (vulpea-db-query-by-file-path file 0))))

(defun my/vulpea-para-set ()
  "Set the current note's PARA property, saving its file.
Operates on the note backing the current buffer when there is one;
otherwise prompts to select any Vulpea note. Value is read via
`completing-read' over `my/vulpea-para-values'."
  (interactive)
  (let* ((note (or (my/vulpea-para--current-note)
                    (vulpea-select "PARA note" :require-match t)))
         (value (completing-read (format "PARA (%s): " (vulpea-note-title note))
                                  my/vulpea-para-values nil t)))
    (let ((buf (or (get-file-buffer (vulpea-note-path note))
                   (find-file-noselect (vulpea-note-path note)))))
      (with-current-buffer buf
        (save-excursion
          (my/vulpea-para--goto note)
          (org-entry-put (point) "PARA" value))
        (save-buffer)))
    (message "%s: PARA -> %s" (vulpea-note-title note) value)))

(defun my/vulpea-para-find (value)
  "Visit a note tagged with PARA value VALUE.
VALUE is read via `completing-read' over `my/vulpea-para-values'.
Queries `vulpea-db-query-by-property', Vulpea's own indexed-property
lookup, so this reads the database rather than grepping files."
  (interactive (list (completing-read "PARA: " my/vulpea-para-values nil t)))
  (let ((notes (vulpea-db-query-by-property "PARA" value)))
    (if notes
        (vulpea-visit (vulpea-select-from (format "PARA: %s" value) notes :require-match t))
      (message "No notes with PARA: %s" value))))

(map! :leader
      (:prefix ("n p" . "para")
       :desc "Set PARA value"     "s" #'my/vulpea-para-set
       :desc "Find by PARA value" "f" #'my/vulpea-para-find))

;; `citar-bibliography' MUST be set at top level, never inside `after!' --
;; Doom's `:tools biblio' module derives `org-cite-global-bibliography' from
;; it inside `(after! oc ...)' (see that module's config.el), so a value that
;; arrives later than the module's own `after! oc' registration is too late
;; and the global bibliography silently stays nil. Same ordering hazard as
;; `oauth2-auto-plstore'. This bit the 2026-08-30 citar spike; see
;; PROJECT.org's notes on that backout. `citar-library-paths' has no such
;; hazard, but is set alongside it for the same reason -- both name paths
;; under `org-directory', consistent with ADR-039's host-agnostic-path
;; convention.
(setq citar-bibliography (expand-file-name "biblio.bib" org-directory)
      citar-library-paths (list (expand-file-name "papers/" org-directory)))

;; Hand-wired note-creation backend: `vulpea-create' instead of
;; `citar-org-roam''s `org-roam-capture-'. Keeps Vulpea the single
;; note-creation entrypoint (same precedent as the hand-rolled Vulpea
;; dailies instead of `org-roam-dailies'). Shape follows
;; `citar-org-roam.el' (`citar-org-roam-notes-config' and its four
;; functions) as a reference for what citar passes in, but targets Vulpea's
;; own API: `vulpea-create' (vulpea.el:1519) to make notes,
;; `vulpea-db-query-by-property'/`-by-property-key' (vulpea-db-query.el:556)
;; to find them by citekey, and `vulpea-visit' to open them by id.
(defconst my/citar-vulpea-citekey-property "CITEKEY"
  "Org property key vulpea literature notes use to record their citekey.
Set by `my/citar-vulpea--create' on every note it creates; queried by
`my/citar-vulpea--items' to find a citekey's notes again.")

(defun my/citar-vulpea--items (&optional keys)
  "Return a hash table mapping each citekey in KEYS to its Vulpea note ids.
KEYS is a list of citekeys, or nil to cover every citekey that has a note --
matches the `:items' contract documented at `citar-notes-sources', which
citar calls with nil to mean \"all\"."
  (let ((table (make-hash-table :test #'equal))
        (notes (if keys
                   (seq-mapcat
                    (lambda (key)
                      (vulpea-db-query-by-property
                       my/citar-vulpea-citekey-property key))
                    keys)
                 (vulpea-db-query-by-property-key
                  my/citar-vulpea-citekey-property))))
    (dolist (note notes)
      (when-let* ((key (cdr (assoc my/citar-vulpea-citekey-property
                                    (vulpea-note-properties note)))))
        (push (vulpea-note-id note) (gethash key table))))
    table))

(defun my/citar-vulpea--hasitems ()
  "Return a predicate: citekey -> non-nil iff it has a Vulpea note.
Matches the `:hasitems' contract at `citar-notes-sources'."
  (let ((table (my/citar-vulpea--items)))
    (lambda (citekey) (and (gethash citekey table) t))))

(defun my/citar-vulpea--open (note-id)
  "Visit the Vulpea note identified by NOTE-ID.
Matches the `:open' contract at `citar-notes-sources' -- NOTE-ID is one of
the ids `my/citar-vulpea--items' put in its hash table, and `vulpea-visit'
(vulpea.el:1144) accepts an id directly."
  (vulpea-visit note-id))

(defun my/citar-vulpea--create (citekey entry)
  "Create (or visit) the Vulpea literature note for CITEKEY/ENTRY.
Matches the `:create' contract at `citar-notes-sources'. Visits the
existing note instead of creating a duplicate if one is already on record
for CITEKEY."
  (if-let* ((existing (car (gethash citekey (my/citar-vulpea--items (list citekey))))))
      (vulpea-visit existing)
    (let ((title (citar-format--entry
                  "${author editor} - ${title} (${date issued year})" entry)))
      (vulpea-create
       title
       :tags '("literature")
       :properties (list (cons my/citar-vulpea-citekey-property citekey))))))

(after! citar
  (citar-register-notes-source
   'vulpea
   (list :name "Vulpea"
         :category 'vulpea-note
         :items #'my/citar-vulpea--items
         :hasitems #'my/citar-vulpea--hasitems
         :open #'my/citar-vulpea--open
         :create #'my/citar-vulpea--create))
  (setq citar-notes-source 'vulpea))

;; Doom's `:tools biblio' module wires `citar-org-roam-mode' -- active
;; because the `org' module's `+roam' flag is on -- via
;; `(after! (citar org-roam) (citar-org-roam-mode))' in its own config.el.
;; That mode's setup function does `(setq citar-notes-source 'citar-org-roam)'
;; the moment org-roam actually loads, which can happen well after citar
;; loads (org-roam is lazy here; nothing forces it at startup), silently
;; undoing the `after! citar' block above. Re-assert here, gated on the same
;; `(citar org-roam)' pair the module uses: module config.el files load
;; before $DOOMDIR's, so this form is queued after the module's for that same
;; load event and always runs last, independent of *when* org-roam ends up
;; loading relative to citar.
(after! (citar org-roam)
  (setq citar-notes-source 'vulpea))

;; Fleeting-note capture: near-zero-friction quick capture into its own
;; ~/org/fleeting.org inbox, separate from the existing "n" template (which
;; keeps its job: task-adjacent notes into todo.org's Inbox). Different
;; lifecycles -- a fleeting note gets processed into a permanent note via
;; this citar/Vulpea pipeline, a task note gets done and archived. Appended
;; with `add-to-list' rather than editing the `org-capture-templates' setq
;; in "Org Agenda and Capture basics" directly, so this workstream's diff
;; stays inside its own anchor heading. Depends on load order: that setq
;; must run first to seed the base list, which it does -- it appears earlier
;; in this file, so its `after! org' registers first and fires first.
(after! org
  (add-to-list 'org-capture-templates
               `("f" "Fleeting note" entry
                 (file ,(expand-file-name "fleeting.org" org-directory))
                 "* %?\n%U" :empty-lines 1)
               'append))

;; org-roam-ui: graph visualization, reading org-roam's OWN sqlite DB, not
;; Vulpea's. org-roam-directory is scoped to ~/org/roam/ only (see "org-roam
;; alongside Vulpea" above) -- so org-roam-ui graphs that one subtree and
;; nothing else. Notes anywhere else under org-directory are absent from the
;; graph entirely, not merely unlinked within it; that is a deliberate,
;; known limitation (zettelkasten-integration-plan.md S6), not a bug to fix
;; here. It is also why later workstreams that want a note graphed place it
;; under ~/org/roam/ on purpose.
(use-package! org-roam-ui
  :after org-roam
  :config
  (setq org-roam-ui-sync-theme t
        org-roam-ui-follow t
        org-roam-ui-update-on-save t
        ;; Upstream's own suggested config defaults this to t (auto-open a
        ;; browser tab). Pinned nil here so enabling the package doesn't
        ;; also mean a browser tab on every Emacs start; launch explicitly
        ;; instead (`org-roam-ui-mode', or `org-roam-ui-open' once running).
        org-roam-ui-open-on-start nil))

;; org-fc: spaced repetition. Natively tag-based discovery
;; (`org-fc-flashcard-tag' defaults to "fc") -- no discovery wrapper needed;
;; an earlier draft of the integration plan assumed one was required and
;; that assumption was wrong (spike in zettelkasten-integration-plan.md S6,
;; S13). `org-fc-directories' already defaults to its own ("~/org/"),
;; identical to `org-directory' (config.org:105); set explicitly below
;; anyway so this doesn't silently ride on an upstream default matching by
;; coincidence.
;;
;; Cards are NOT created by hand-adding the "fc" tag. The tag alone isn't a
;; valid card -- it's missing the FC_TYPE/FC_CREATED properties and
;; REVIEW_DATA drawer that scheduling depends on. Run
;; `org-fc-type-normal-init' or `org-fc-type-cloze-init' on a heading (or
;; the hydra, `org-fc-hydra/body'), which writes all of that together.
(use-package! org-fc
  :commands (org-fc-review org-fc-hydra/body)
  :config
  (setq org-fc-directories '("~/org/")))

(map! :leader
      :desc "Flashcard review (org-fc)" "n R" #'org-fc-review)

;; org-transclusion: embeds a *live*, read-only copy of another note's
;; content into the current buffer via a `#+transclude:' keyword line,
;; instead of copy-pasting it -- the source stays the single writable copy.
;; This is the mechanism the system-notes generator below depends on
;; ([[id:system-notes-generator-anchor]]): a personal note transcludes the
;; generator's disposable output rather than annotating it directly, so a
;; regenerate can overwrite the generated file wholesale without eating any
;; hand-written text (see the plan, workstream 6). No global config needed --
;; it "requires no additional configuration" per its own docs -- and it's a
;; per-buffer minor mode, toggled rather than hooked into every org buffer so
;; files that never transclude anything don't pay its refresh cost.
(use-package! org-transclusion
  :commands (org-transclusion-mode org-transclusion-add org-transclusion-remove))

;; consult-notes: one Vertico/consult-based note finder spanning every note
;; source in play, wired per its own docs (mclear-tools/consult-notes).
;; `consult-notes-file-dir-sources' covers `org-directory' as plain files --
;; this is also how Vulpea notes surface here, since Vulpea has no consult
;; integration of its own and a Vulpea note is just an .org file (with an
;; `ID') somewhere under this tree. `consult-notes-org-roam-mode' adds a
;; second, richer (title/backlink-aware) source scoped to the `~/org/roam/'
;; subtree specifically. The two sources overlap on files under
;; `~/org/roam/' -- expected, not a bug: the org-roam source is strictly more
;; informative for those files, and consult just shows both.
(use-package! consult-notes
  :commands (consult-notes consult-notes-search-in-all-notes)
  :config
  (setq consult-notes-file-dir-sources
        `(("Org notes" ?o ,org-directory)))
  (consult-notes-org-roam-mode))

;; Both live under the same `SPC n x' ("notes extras") prefix, mirroring how
;; the Vulpea workstream above got its own `SPC n v' prefix.
(map! :leader
      (:prefix ("n x" . "notes extras")
       :desc "Toggle transclusion mode"     "t" #'org-transclusion-mode
       :desc "Add transclusion at point"    "a" #'org-transclusion-add
       :desc "Remove transclusion at point" "r" #'org-transclusion-remove
       :desc "Find note (consult)"          "f" #'consult-notes
       :desc "Search all notes (consult)"   "s" #'consult-notes-search-in-all-notes))

(load! "system-notes")

;; Interactive trigger only -- never wired into `doom sync' or any hook (per
;; the plan's explicit non-goal). Lives under the existing "n v" (vulpea)
;; prefix rather than opening a new bare "n" slot, since these are Vulpea-
;; indexed notes and that prefix is already this repo's home for Vulpea
;; commands (see the Vulpea backlinks buffer section above for the rest of
;; that prefix's bindings: f/b/i/s/d/B/j/J/p/n -- "g" is unused).
(map! :leader
      (:prefix ("n v" . "vulpea")
       :desc "Generate system notes" "g" #'my/system-notes-generate))

;; Calendar: calfw view + two-way org-gcal sync (docs/decisions.org ADR-025).
;; The `:app calendar' module already ships calfw's evil keymap, its popup rule
;; and the `=calendar' command, so only credentials, the calendar-to-file
;; mapping and the two sync triggers belong here.
;;
;; Credentials come from the same Google Cloud OAuth client mu4e uses
;; (`mail/oauth2-google-client', ADR-011). Unlike gptel's backends above, these
;; can't stay behind a lambda: org-gcal reads `org-gcal-client-id' and
;; `org-gcal-client-secret' literally as it loads and copies them into
;; `oauth2-auto-additional-providers-alist', so they must be real strings in
;; the variables, followed by `org-gcal-reload-client-id-secret' to rebuild
;; that alist. Load is deferred to first calendar use, so the gpg prompt still
;; doesn't happen at startup. The one-time "must set `org-gcal-client-id'"
;; warning is expected -- org-gcal emits it a moment before this block runs.
;;
;; Tokens are oauth2-auto's business (`oauth2-auto-plstore'), not org-gcal's:
;; the module's `org-gcal-token-file' defvar is vestigial in this version.
;;
;; ~/org/calendar/ is org-gcal-owned -- it rewrites the files it syncs, so
;; nothing hand-written goes in there. The agenda picks it up for free, since
;; `org-agenda-files' is the whole of `org-directory' (ADR-017).

;; Keep the OAuth token store out of `user-emacs-directory' (oauth2-auto's
;; default), which here is Doom's own git checkout. `doom-state-dir' is the
;; right shelf for it: losing the file only costs a re-authorization. Set at
;; config load rather than inside the `after!' below, because the agenda hook
;; checks this path before anything has loaded org-gcal -- a `defcustom' won't
;; overwrite a value the variable already has.
(setq oauth2-auto-plstore (expand-file-name "oauth2-auto.plist" doom-state-dir))

(after! org-gcal
  (setq org-gcal-client-id
        (+pass-get-field "mail/oauth2-google-client"
                         '("client_id" "client-id" "login" "user") 'noerror)
        org-gcal-client-secret
        (+pass-get-field "mail/oauth2-google-client" 'secret 'noerror)
        org-gcal-fetch-file-alist
        `(("mrniceguyjames@gmail.com"
           . ,(expand-file-name "calendar/personal.org" org-directory))
          ("jcook@ualberta.ca"
           . ,(expand-file-name "calendar/ualberta.org" org-directory))))
  ;; Both lookups pass NOERROR deliberately. `+pass-get-secret' would signal on
  ;; a missing or unreadable entry, and that signal propagates out of the
  ;; `require' inside `org-gcal-sync' -- which, from the agenda hook below,
  ;; breaks opening the agenda at all. Degrade to a warning instead: the
  ;; calendar stays unauthenticated, `SPC n a' still works.
  (if (and org-gcal-client-id org-gcal-client-secret)
      (org-gcal-reload-client-id-secret)
    (warn "org-gcal: no usable OAuth client in pass entry mail/oauth2-google-client")))

;; Sync triggers (ADR-025): `SPC o C' always syncs, while opening the agenda
;; syncs at most once an hour -- without that staleness guard every `SPC n a'
;; would cost a round-trip to Google. `org-gcal-sync' is deferred-async, so
;; neither trigger blocks; a hung call degrades to stale data rather than a
;; frozen agenda. The lock check matters: `org-gcal-sync' signals a
;; `user-error' while a previous sync is still running (or died holding the
;; lock), which from a hook would break opening the agenda outright. Clear a
;; stuck lock with `org-gcal--sync-unlock'.
(defvar my/org-gcal-sync-min-interval 3600
  "Seconds an agenda-open sync must be stale before another one runs.")

(defvar my/org-gcal-last-sync 0
  "`float-time' of the last agenda-open sync.")

(defun my/org-gcal-sync-maybe ()
  "Sync Google Calendar if the last agenda-open sync has gone stale.
Skips the sync entirely when no oauth2-auto token store exists yet. With no
stored token, `org-gcal-sync' starts an authorization flow -- a browser hand-off
and, in oauth2-auto's manual mode, a blocking `read-string' for the returned
code (oauth2-auto.el:500). Neither belongs in a hook that fires while the
agenda is being drawn. Authorizing is a user-initiated act: do it once via
`SPC o C', after which this hook has a token to refresh silently."
  (when (and (> (- (float-time) my/org-gcal-last-sync)
                my/org-gcal-sync-min-interval)
             (not (bound-and-true-p org-gcal--sync-lock))
             (require 'oauth2-auto nil t)
             (file-exists-p oauth2-auto-plstore))
    (setq my/org-gcal-last-sync (float-time))
    (org-gcal-sync nil 'silent)))

(add-hook 'org-agenda-mode-hook #'my/org-gcal-sync-maybe)

(map! :leader
      :desc "Calendar (calfw)"         "o c" #'=calendar
      :desc "Calendar sync (org-gcal)" "o C" #'org-gcal-sync)

;; emacs-everywhere buffers must not get a file template (ADR-032).
;;
;; `emacs-everywhere' opens a brand-new temp file (`/tmp/emacs-everywhere-<ts>-<app>')
;; with no extension, so it visits in `fundamental-mode' and no template rule
;; matches. Then `emacs-everywhere-apply-major-mode' switches it to `org-mode'
;; -- `pandoc' is installed, so `emacs-everywhere-major-mode-function' defaults
;; to `org-mode' rather than markdown. The buffer is now empty, unmodified,
;; backed by a file that doesn't exist yet, and in a mode with a template rule.
;; Doom checks templates on `doom-switch-buffer-hook' (not `find-file-hook'),
;; so the *next* switch into that buffer fires `+file-templates-check-h', every
;; condition passes, and org-mode's `__' template inserts
;; `#+title: Emacs Everywhere 20260823 141530 Firefox' -- which then gets pasted
;; straight back into whatever app you invoked it from.
;;
;; `emacs-everywhere-init-hooks' runs before `emacs-everywhere-mode' and before
;; any later buffer switch, so inhibiting there wins the race. Same mechanism
;; and same hook the module itself uses one line over for
;; `doom-inhibit-local-var-hooks'.
(after! emacs-everywhere
  (setq-hook! 'emacs-everywhere-init-hooks +file-templates-inhibit t))

;; EXWM
;; (defun my/exwm-screen-layout ()
;;   "Configure monitors: external on the left of the laptop."
;;   (start-process-shell-command
;;    "xrandr" nil
;;    ;; External HDMI-1 on the left, laptop eDP-1 on the right
;;    "xrandr --output HDMI-1 --auto --left-of eDP-1 --output eDP-1 --auto --primary"))

;; ;; Apply once at startup
;; (add-hook 'exwm-init-hook #'my/exwm-screen-layout)

;; ;; Optional: re-apply on EXWM restart (only if your EXWM provides this hook)
;; (when (boundp 'exwm-restart-hook)
;;   (add-hook 'exwm-restart-hook #'my/exwm-screen-layout))

;; ;; RandR integration (multi-monitor awareness)
;; (require 'exwm-randr)

;; ;; Re-apply layout when screens change (dock/undock, power cycle, etc.)
;; (add-hook 'exwm-randr-screen-change-hook #'my/exwm-screen-layout)

;; ;; Optional: pin workspaces to monitors
;; ;; 0–4 on HDMI-1 (left), 5–9 on eDP-1 (right)
;; (setq exwm-randr-workspace-output-plist
;;       '(0 "HDMI-1" 1 "HDMI-1" 2 "HDMI-1" 3 "HDMI-1" 4 "HDMI-1"
;;         5 "eDP-1"  6 "eDP-1"  7 "eDP-1"  8 "eDP-1"  9 "eDP-1"))

;; (exwm-randr-mode 1)

;; ;; Make class name the buffer name
;; (add-hook 'exwm-update-class-hook
;;           (lambda ()
;;             (exwm-workspace-rename-buffer exwm-class-name)))

;; ;; Global keybindings.
;; (unless (get 'exwm-input-global-keys 'saved-value)
;;   (setq exwm-input-global-keys
;;         `(
;;           ;; Helpful Commands
;;           ([?\s-/] . exwm-input-release-keyboard)
;;           ([?\s-?] . exwm-reset)
;;           ;; Toggles
;;           ([?\s-F] . exwm-floating-hide)
;;           ([?\s-f] . exwm-floating-toggle-floating)
;;           ([?\s-m] . exwm-layout-toggle-mode-line)
;;           ([f11] . exwm-layout-toggle-fullscreen)
;;           ;; Workspace Management
;;           ([?\s-w] . exwm-workspace-switch)
;;           ([?\s-W] . exwm-workspace-swap)
;;           ([?\s-\C-w] . exwm-workspace-move)
;;           ;; Switch workspace with super+[0-9]
;;           ([?\s-0] . (lambda () (interactive) (exwm-workspace-switch-create 0)))
;;           ([?\s-1] . (lambda () (interactive) (exwm-workspace-switch-create 1)))
;;           ([?\s-2] . (lambda () (interactive) (exwm-workspace-switch-create 2)))
;;           ([?\s-3] . (lambda () (interactive) (exwm-workspace-switch-create 3)))
;;           ([?\s-4] . (lambda () (interactive) (exwm-workspace-switch-create 4)))
;;           ([?\s-5] . (lambda () (interactive) (exwm-workspace-switch-create 5)))
;;           ([?\s-6] . (lambda () (interactive) (exwm-workspace-switch-create 6)))
;;           ([?\s-7] . (lambda () (interactive) (exwm-workspace-switch-create 7)))
;;           ([?\s-8] . (lambda () (interactive) (exwm-workspace-switch-create 8)))
;;           ([?\s-9] . (lambda () (interactive) (exwm-workspace-switch-create 9)))
;;           ;; Window Management
;;           ([?\s-\C-v] . evil-window-vsplit)
;;           ([?\s-z] . evil-window-split)
;;           ([?\s-b] . ibuffer)
;;           ([?\s-B] . kill-current-buffer)
;;           ([?\s-C] . +workspace/close-window-or-workspace)
;;           ([?\s-x] . doom/open-scratch-buffer)
;;           ;; Change window focus with super+h,j,k,l
;;           ([?\s-h] . evil-window-left)
;;           ([?\s-j] . evil-window-down)
;;           ([?\s-k] . evil-window-up)
;;           ([?\s-l] . evil-window-right)
;;           ;; Move windows around using super+shift+h,j,k,l
;;           ([?\s-H] . +evil/window-move-left)
;;           ([?\s-J] . +evil/window-move-down)
;;           ([?\s-K] . +evil/window-move-up)
;;           ([?\s-L] . +evil/window-move-right)
;;           ;; Essential Programs
;;           ([?\s-d] . dired)
;;           ([?\s-t] . (lambda () (interactive)
;;                        (start-process-shell-command "terminal" "*terminal*" "xfce4-terminal")))
;;           ;; Launch application.
;;           ([?\M-\s-7] . (lambda (command)
;;                           (interactive (list (read-shell-command "$ ")))
;;                           (start-process-shell-command command nil command))))))

;; ;; Line-editing shortcuts
;; (unless (get 'exwm-input-simulation-keys 'saved-value)
;;   (setq exwm-input-simulation-keys
;;         '(([?\C-b] . [left])
;;           ([?\C-f] . [right])
;;           ([?\C-p] . [up])
;;           ([?\C-n] . [down])
;;           ([?\C-a] . [home])
;;           ([?\C-e] . [end])
;;           ([?\M-v] . [prior])
;;           ([?\C-v] . [next])
;;           ([?\C-d] . [delete])
;;           ([?\C-k] . [S-end delete])
;;           ([?\s-c] . [?\C-c])
;;           ([?\s-v] . [?\C-v]))))

;; ;; Enable EXWM
;; (exwm-enable)

;; ;; Open Workspaces and start programs?
