;;; $DOOMDIR/config.el -*- lexical-binding: t; -*-

;; Place your private configuration here! Remember, you do not need to run 'doom
;; sync' after modifying this file!

;; Doom's env cache (05-doom-env.load.el, regenerated by `doom sync --env')
;; loads unconditionally on every startup, before this file. If it was ever
;; regenerated from inside a Claude Code CLI subprocess shell (which any
;; agent's shell always is), it bakes in that shell's ephemeral,
;; subprocess-only Claude Code identity vars (CLAUDECODE, CLAUDE_JOB_DIR,
;; CLAUDE_CODE_SESSION_ID, etc.) as permanent config, so every `claude'
;; process later launched from Emacs (e.g. via claude-code-ide.el) inherits a
;; dead session's identity instead of a fresh one. Since this file is the one
;; thing Doom loads last, every startup, regardless of what's cached, strip
;; those vars here defensively rather than relying on the cache staying
;; clean. See docs/decisions.org ADR-013 and
;; docs/ai/troubleshooting.org::tshoot-claude-env-leak for the full incident.
(setq process-environment
      (seq-remove
       (lambda (entry) (string-match-p "\\`\\(CLAUDECODE\\|CLAUDE_[A-Z_]*\\|AI_AGENT\\)=" entry))
       process-environment))


;; Some functionality uses this to identify you, e.g. GPG configuration, email
;; clients, file templates and snippets. It is optional.
;; (setq user-full-name "John Doe"
;;       user-mail-address "john@doe.com")

;; Doom exposes five (optional) variables for controlling fonts in Doom:
;;
;; - `doom-font' -- the primary font to use
;; - `doom-variable-pitch-font' -- a non-monospace font (where applicable)
;; - `doom-big-font' -- used for `doom-big-font-mode'; use this for
;;   presentations or streaming.
;; - `doom-symbol-font' -- for symbols
;; - `doom-serif-font' -- for the `fixed-pitch-serif' face
;;
;; See 'C-h v doom-font' for documentation and more examples of what they
;; accept. For example:
;;
;;(setq doom-font (font-spec :family "Fira Code" :size 12 :weight 'semi-light)
;;      doom-variable-pitch-font (font-spec :family "Fira Sans" :size 13))
;;
;; If you or Emacs can't find your font, use 'M-x describe-font' to look them
;; up, `M-x eval-region' to execute elisp code, and 'M-x doom/reload-font' to
;; refresh your font settings. If Emacs still can't find your font, it likely
;; wasn't installed correctly. Font issues are rarely Doom issues!

;; There are two ways to load a theme. Both assume the theme is installed and
;; available. You can either set `doom-theme' or manually load a theme with the
;; `load-theme' function. This is the default:
(setq doom-theme 'doom-zenburn)

;; This determines the style of line numbers in effect. If set to `nil', line
;; numbers are disabled. For relative line numbers, set this to `relative'.
(setq display-line-numbers-type 'relative)

;; If you use `org' and don't want your org files in the default location below,
;; change `org-directory'. It must be set before org loads!
(setq org-directory "~/org/")


;; Whenever you reconfigure a package, make sure to wrap your config in an
;; `after!' block, otherwise Doom's defaults may override your settings. E.g.
;;
;;   (after! PACKAGE
;;     (setq x y))
;;
;; The exceptions to this rule:
;;
;;
;;   - Setting file/directory variables (like `org-directory')
;;   - Setting variables which explicitly tell you to set them before their
;;     package is loaded (see 'C-h v VARIABLE' to look up their documentation).
;;   - Setting doom variables (which start with 'doom-' or '+').
;;
;; Here are some additional functions/macros that will help you configure Doom.
;;
;; - `load!' for loading external *.el files relative to this one
;; - `use-package!' for configuring packages
;; - `after!' for running code after a package has loaded
;; - `add-load-path!' for adding directories to the `load-path', relative to
;;   this file. Emacs searches the `load-path' when you load packages with
;;   `require' or `use-package'.
;; - `map!' for binding new keys
;;
;; To get information about any of these functions/macros, move the cursor over
;; the highlighted symbol at press 'K' (non-evil users must press 'C-c c k').
;; This will open documentation for it, including demos of how they are used.
;; Alternatively, use `C-h o' to look up a symbol (functions, variables, faces,
;; etc).
;;
;; You can also try 'gd' (or 'C-c c d') to jump to their definition and see how
;; they are implemented.

;; Maximize every new graphical frame, and resize splash screen.
;;
;; Without `frame-resize-pixelwise', Emacs quantizes its frame to whole
;; character-cell dimensions any time the size changes -- including right
;; after the window manager maximizes it. On GNOME/Mutter (Ubuntu) that
;; immediate "round back down to a cell boundary" resize reads as the app
;; rejecting the maximize, so Mutter reverts the state instantly -- the frame
;; never visibly grows at all. xfwm4 (Xubuntu) tolerates the mismatch and
;; leaves it maximized regardless, which is why this only shows up on Ubuntu.
(setq frame-resize-pixelwise t)

;; Belt-and-suspenders: even with pixelwise resizing, GNOME/Mutter can still
;; ignore a `fullscreen' request sent right at frame creation (the frame
;; isn't mapped onto the display yet), unlike xfwm4, which applies it
;; immediately. Reasserting it a few times over the following moments is a
;; self-healing workaround -- setting `fullscreen' to a value it already has
;; is a no-op, so this is harmless once it "sticks". Hooking
;; `after-make-frame-functions' (rather than only
;; `server-after-make-frame-hook') also covers frames created outside the
;; emacsclient protocol, e.g. claude-code-ide.el's own frame.
(defun +my/maximize-frame (frame)
  (when (display-graphic-p frame)
    (dolist (delay '(0 0.1 0.3))
      (run-with-timer delay nil
                       (lambda ()
                         (when (frame-live-p frame)
                           (set-frame-parameter frame 'fullscreen 'maximized)))))))
(add-hook 'after-make-frame-functions #'+my/maximize-frame)

;; ROOT CAUSE (found 2026-08-17): `after-make-frame-functions' is documented
;; to never run for the very first frame of a session -- that frame already
;; exists before this hook is installed. So the maximize logic above only
;; ever ran for *subsequent* frames (emacsclient, claude-code-ide.el's own
;; frame, C-x 5 2) and never for the frame you actually see at startup --
;; confirmed live: zero `+my/maximize-frame' messages logged despite the
;; frame existing. None of the undecorated/pixelwise theories were it; the
;; startup frame's maximize call simply never fired. Call it directly once
;; that frame exists.
(add-hook 'window-setup-hook
          (lambda () (+my/maximize-frame (selected-frame))))

;; Only take over a bare `emacsclient -c' frame (e.g. a terminal alias that
;; pops a blank Emacs frame) with the dashboard -- never a frame that was
;; asked to visit a specific file, e.g. Magit's `git commit' opening
;; COMMIT_EDITMSG via `with-editor'/`emacsclient'. The guard has to inspect
;; FRAME's *window*, not `buffer-file-name': `select-frame'/
;; `with-selected-frame' select the frame (and its window), but do NOT
;; sync `current-buffer' to that window's buffer -- `buffer-file-name' here
;; reads whatever buffer happened to be current in this timer callback's
;; execution context, which has nothing to do with FRAME. Confirmed live
;; (2026-08-20): even with COMMIT_EDITMSG correctly showing in the frame,
;; `(with-selected-frame frame (unless buffer-file-name ...))' saw a
;; stale/unrelated current-buffer and opened the dashboard anyway. A prior
;; fix (69a66c2) added this timer+guard for the same symptom but checked
;; `buffer-file-name' the same wrong way, so it never actually worked --
;; see docs/ai/troubleshooting.org::tshoot-dashboard-stomps-commit-buffer.
(add-hook 'server-after-make-frame-hook
          (lambda ()
            (let ((frame (selected-frame)))
              (run-with-timer
               0.1 nil
               (lambda ()
                 (when (frame-live-p frame)
                   (unless (buffer-file-name
                            (window-buffer (frame-selected-window frame)))
                     (with-selected-frame frame
                       (+dashboard/open frame)))))))))

(add-to-list 'default-frame-alist '(undecorated . t))

;; Center text and limit line width for better readability
(use-package! perfect-margin
  :custom
  (perfect-margin-visible-width 100)  ; adjust to your preferred text column width
  :config
  (perfect-margin-mode t)
  (after! doom-modeline
    (setq mode-line-right-align-edge 'right-fringe)))

;; Better default behavior
;;     - No permanent deletion, use trash
;;     - Smoother scrolling
;;     - Don't bother confirming if you want to leave emacs
(setq delete-by-moving-to-trash t
      scroll-margin 8
      scroll-conservatively 101
      confirm-kill-emacs nil)

;; Doom modeline mods
(after! doom-modeline
  ;; 1) Size / spacing
  (setq doom-modeline-height 28          ; modeline height (pixels-ish)
        doom-modeline-bar-width 3        ; left bar width
        doom-modeline-window-width-limit 85) ; hide extra info in narrow windows

  ;; 2) Icons (turn off if you want max speed / no nerd fonts)
  (setq doom-modeline-icon t
        doom-modeline-major-mode-icon t
        doom-modeline-major-mode-color-icon t)

  ;; 3) File name style (popular: show relative name from project)
  (setq doom-modeline-buffer-file-name-style 'relative-to-project)

  ;; 4) Common “noise” toggles
  (setq doom-modeline-minor-modes nil    ; hides minor modes list (usually noisy)
        doom-modeline-mu4e nil
        doom-modeline-gnus nil)

  ;; 5) Git + diagnostics (popular to keep on)
  (setq doom-modeline-vcs t
        doom-modeline-checker-simple-format t)

  ;; 6) Extra info (pick what you like)
  (setq doom-modeline-indent-info nil    ; show indent info (spaces/tabs)
        doom-modeline-buffer-encoding nil ; hide UTF-8, etc. (usually not needed)
        doom-modeline-time nil           ; set to t if you want a clock
        doom-modeline-battery nil))      ; set to t on laptops

;; --- Rice pass (docs/decisions.org ADR-022) -------------------------------
;; Theme stays doom-zenburn; this section covers font, transparency, cursor
;; motion feedback, zen-mode focus dimming, and the dashboard banner.

;; Font: "JetBrains Mono" (plain, via apt's `fonts-jetbrains-mono' -- the
;; Nerd-patched variant needed GitHub, which this sandbox couldn't reach) for
;; both faces; `:ui zen's mixed-pitch-mode wants a variable-pitch font to
;; switch to. Icon glyph coverage doesn't need the primary font itself to be
;; Nerd-patched: `Symbols Nerd Font Mono' (already installed, and exactly
;; what `nerd-icons.el' pairs with any regular font as a fallback) covers
;; that via Emacs's normal fontset fallback. `M-x describe-font' confirms
;; this actually took effect.
(setq doom-font (font-spec :family "JetBrains Mono" :size 13)
      doom-variable-pitch-font (font-spec :family "JetBrains Mono" :size 13))

;; Transparency: native Emacs 29+ alpha-background compositing -- no external
;; compositor needed (confirmed: this build is Cairo-enabled). Unfocused
;; frames fade further so the active window visually pops.
;; `after-focus-change-function' (not the obsolete-since-27.1
;; `focus-in-hook'/`focus-out-hook') is the correct modern hook, and it fires
;; per-frame-list rather than assuming a single frame, which matters here
;; since Emacs runs as a daemon with frames created via emacsclient.
(add-to-list 'default-frame-alist '(alpha-background . 92))
(defun +my/rice-update-frame-alpha ()
  "Fade every unfocused frame's alpha-background; keep the focused one clearer."
  (dolist (frame (frame-list))
    (set-frame-parameter frame 'alpha-background
                          (if (eq frame (selected-frame)) 92 80))))
(add-function :after after-focus-change-function #'+my/rice-update-frame-alpha)

;; Cursor motion feedback: pulsar (animated colored pulse) instead of Doom's
;; plain :ui nav-flash blink module (disabled in init.el) -- running both
;; would double-fire on the same events. Pulsar's own default
;; `pulsar-pulse-functions' already covers the common Evil big-motion
;; commands (evil-goto-line, evil-scroll-*, evil-window-top/bottom, etc.) and
;; `other-window' -- only `switch-to-buffer' was missing from that list.
(use-package! pulsar
  :hook (doom-first-input . pulsar-global-mode)
  :config
  (setq pulsar-delay 0.06
        pulsar-iterations 8
        pulsar-face 'pulsar-cyan)
  (add-to-list 'pulsar-pulse-functions 'switch-to-buffer))

;; Dashboard: ASCII banner spelling this machine's hostname, generated at
;; render time via `figlet' (a tiny, standard Unix tool -- matches this
;; config's existing pattern of shelling out to well-known external tools,
;; e.g. ruff/black/xdotool elsewhere in this file) rather than a hand-rolled
;; Elisp font table or a hardcoded name, so the banner stays correct if this
;; config is ever used on a different machine. Overrides
;; `+dashboard-ascii-banner-fn' (a doom `+' variable, so no `after!' wrapper
;; needed, matching the exemption already documented above). Falls back to
;; plain `(system-name)' text if `figlet' isn't installed, rather than
;; erroring the dashboard.
(defun +my/dashboard-hostname-banner-fn ()
  "Return an ASCII banner of `(system-name)', rendered via figlet."
  (propertize
   (if (executable-find "figlet")
       (string-trim-right
        (shell-command-to-string
         (format "figlet -f standard %s"
                 (shell-quote-argument (system-name)))))
     (system-name))
   'face '+dashboard-banner))
(setq +dashboard-ascii-banner-fn #'+my/dashboard-hostname-banner-fn)
;; --- end rice pass ---------------------------------------------------------

;; centaur-tabs' new-tab button (the `+' at the right end of the tab bar) and
;; its interactive equivalent both funnel through
;; `centaur-tabs--create-new-tab', which opens a blank "Untitled" buffer.
;; Override that single chokepoint so both entry points land on the Doom
;; dashboard instead -- the dashboard is already this config's fallback buffer
;; (`doom-fallback-buffer'), so a new tab and an emptied frame agree on what
;; "nothing open" looks like.
;;
;; The dashboard is a singleton buffer (`+dashboard-name', "*doom*"), so this
;; selects the existing dashboard tab rather than stacking up new ones; that's
;; deliberate, since `+dashboard-reload' renders into that one buffer.
(after! centaur-tabs
  (defun +my/centaur-tabs-new-tab-dashboard (&rest _)
    "Open the Doom dashboard instead of an Untitled buffer."
    (interactive)
    (+dashboard/open (selected-frame)))
  (advice-add 'centaur-tabs--create-new-tab :override
              #'+my/centaur-tabs-new-tab-dashboard)

  ;; Doom's `:ui tabs' module installs
  ;; `+tabs-disable-centaur-tabs-mode-maybe-h' on `+dashboard-mode-hook'; it
  ;; *enables* `centaur-tabs-local-mode' there, whose on-state means "hide
  ;; the bar in this buffer". Without removing it the tab bar would vanish
  ;; the instant the new tab opens, leaving no visible way back to the other
  ;; tabs -- self-defeating for a button whose whole job is opening a tab.
  ;;
  ;; The module adds the same function to `+doom-dashboard-mode-hook' too,
  ;; but nothing in Doom runs that deprecated name any more, so removing it
  ;; from `+dashboard-mode-hook' alone is sufficient.
  (remove-hook '+dashboard-mode-hook #'+tabs-disable-centaur-tabs-mode-maybe-h))

;; centaur-tabs ships no keybindings of its own; Doom's `:ui tabs' module only
;; adds `gt'/`gT' (`+tabs:next-or-goto', which take a count -- `4gt' jumps to
;; the 4th visible tab). These fill in the operations that otherwise need M-x.
;;
;; `ga' deliberately shadows evil's `what-cursor-position' -- that command is
;; a debugging curiosity, tab-jumping is a per-minute operation. `M-x
;; what-cursor-position' and `C-x =' both still reach it.
;;
;; New-tab lives under `SPC b' rather than `SPC t' (toggle): a centaur tab
;; *is* a buffer, so it belongs next to `SPC b N' (new empty buffer), and
;; opening a tab isn't a toggle.
(map! :after centaur-tabs
      :n "ga" #'centaur-tabs-ace-jump           ; C-u swaps, C-u C-u closes
      :n "g<" #'centaur-tabs-move-current-tab-to-left
      :n "g>" #'centaur-tabs-move-current-tab-to-right
      (:leader
       (:prefix "b"
        :desc "New tab (dashboard)"  "t" #'centaur-tabs--create-new-tab
        :desc "Switch tab group"     "T" #'centaur-tabs-switch-group
        :desc "Kill other tabs (group)" "o" #'centaur-tabs-kill-other-buffers-in-current-group)))

;; Save minibuffer history (Vertico likes this)
(after! savehist
  (savehist-mode 1))

;; Preview results as you move (feel free to set to nil if annoying)
(after! consult
  (setq consult-preview-key "M-."))

(map! :leader
      :desc "Search project (ripgrep)" "s p" #'consult-ripgrep)

(after! projectile
  (setq projectile-project-search-path '("~/Documents/")
        projectile-indexing-method 'alien) ; uses external tools (fast)
  (add-to-list 'projectile-globally-ignored-directories ".venv")
  (add-to-list 'projectile-globally-ignored-directories "__pycache__")
  (add-to-list 'projectile-globally-ignored-directories ".mypy_cache")
  (add-to-list 'projectile-globally-ignored-directories ".ruff_cache"))

(after! projectile
  (dolist (p '(".venv" "venv" "__pycache__" ".mypy_cache" ".pytest_cache" ".ruff_cache"))
    (add-to-list 'projectile-globally-ignored-directories p)))

(map! :leader :desc "Magit status" "g s" #'magit-status)

;; Ghostel in project root (migrated from vterm 2026-08-17, see ADR-014;
;; my/project-vterm's whole reason for existing -- vterm doesn't offer a
;; project-root-scoped entry point of its own -- carries over unchanged,
;; just swapping which terminal backend it opens).
(defun my/project-ghostel ()
  "Open ghostel in the current project's root."
  (interactive)
  (let ((default-directory (projectile-project-root)))
    (ghostel)))

(map! :leader :desc "Project ghostel" "p t" #'my/project-ghostel)

;; vterm didn't repaint reliably when its window was resized while it wasn't
;; the selected window (a known vterm/libvterm bug class). This was worked
;; around here via a window-size-fixed freeze on vterm-mode-hook (added
;; 2026-08-07, removed 2026-08-17 when vterm itself was migrated away from —
;; see ADR-014). Not carried over to ghostel: no equivalent corruption has
;; been observed, and claude-code-ide.el already actively re-syncs ghostel's
;; process window size on resize (see claude-code-ide.el's
;; ghostel--window-adjust-process-window-size call), which vterm never had.
;; If the same visual-corruption symptom ever recurs under ghostel, revisit
;; with an equivalent freeze scoped to ghostel-mode-hook instead.

(after! envrc
  (envrc-global-mode))

;; Python IDE Setup
(after! flycheck
  (flycheck-define-checker python-ruff
    "A Python linter using Ruff."
    :command ("ruff" "check"
              "--output-format" "concise"
              "--stdin-filename" source-original
              "-")
    :standard-input t
    :error-patterns
    ((error line-start (file-name) ":" line ":" column ": " (message) line-end))
    :modes (python-mode python-ts-mode))

  (add-to-list 'flycheck-checkers 'python-ruff))

(after! (flycheck lsp-mode)
  (defun my/python-flycheck-chain-lsp-then-ruff ()
    "In Python buffers, run LSP diagnostics first, then Ruff."
    (when (and (memq major-mode '(python-mode python-ts-mode))
               (bound-and-true-p lsp-mode)
               (flycheck-valid-checker-p 'lsp)
               (flycheck-valid-checker-p 'python-ruff))
      (setq-local flycheck-checker 'lsp)
      (flycheck-remove-next-checker 'lsp 'python-ruff)
      (flycheck-add-next-checker 'lsp 'python-ruff 'append)))

  (add-hook 'lsp-managed-mode-hook #'my/python-flycheck-chain-lsp-then-ruff))


(after! python
  ;; Use Black as the formatter for Python (file-based, respects pyproject.toml)
  (set-formatter! 'black '("black" "-q" "--stdin-filename" (or buffer-file-name "stdin.py") "-"))
  (setq-hook! 'python-mode +format-with 'black)
  (setq-hook! 'python-ts-mode +format-with 'black))

(defun my/python-ruff-fix-buffer ()
  "Run `ruff check --fix` on a temp file, then replace the buffer with the fixed code.
Does not write to disk unless you save."
  (interactive)
  (unless (executable-find "ruff")
    (user-error "Ruff not found on PATH"))
  (unless buffer-file-name
    (user-error "Save the file once so Ruff can resolve project settings"))

  (let* ((root (or (locate-dominating-file default-directory "pyproject.toml")
                   default-directory))
         (tmp  (make-temp-file (expand-file-name "ruff-fix-" root) nil ".py"))
         (orig (buffer-string))
         (orig-point (point)))
    (unwind-protect
        (progn
          ;; write buffer to temp file
          (with-temp-file tmp
            (insert orig))

          ;; run ruff fix on temp file; ignore exit code
          (call-process "ruff" nil "*ruff-fix*" nil
                        "check" "--fix" tmp)

          ;; read fixed temp file back into buffer
          (let ((fixed (with-temp-buffer
                         (insert-file-contents tmp)
                         (buffer-string))))
            (if (string= orig fixed)
                (message "Ruff: no changes")
              (erase-buffer)
              (insert fixed)
              (goto-char (min orig-point (point-max)))
              (message "Ruff: fixes applied to buffer (not saved)"))))
      (when (file-exists-p tmp)
        (delete-file tmp)))))

(map! :after python
      :map (python-mode-map python-ts-mode-map)
      :localleader
      "r f" #'my/python-ruff-fix-buffer)

(after! lsp-pyright
  (setq lsp-pyright-typechecking-mode "strict"))

;; Add jk as an escape sequence
(after! evil-escape
  (setq evil-escape-key-sequence "jk"
        evil-escape-delay 0.20)
  (evil-escape-mode 1))

;; AI: chat and focused transformation via gptel.
;; `:tools llm' owns gptel itself -- its package pin, `gptel-default-mode',
;; `gptel-display-buffer-action' and popup rule, the `SPC o l' keybinds, plus
;; gptel-magit/gptel-quick/ob-gptel. Only backend credentials and directives
;; live here; don't restate module defaults.
;; Credentials come from Doom's `:tools pass' module (`+auth' flag), never
;; hand-rolled shell wrappers. See docs/ai/providers.org for the full
;; credential map and docs/decisions.org ADR-003/004 for why the leader
;; namespace and provider choices look like this.
(after! gptel
  ;; Anthropic is the default backend. `:models' is deliberately omitted on
  ;; both backends below -- gptel ships and maintains its own current model
  ;; registry (gptel--anthropic-models / gptel--openai-models), so omitting
  ;; `:models' tracks upstream automatically instead of hardcoding names that
  ;; will be stale within months.
  (setq-default
   gptel-backend (gptel-make-anthropic "Claude"
                   :key (lambda () (+pass-get-secret "api/anthropic"))
                   :stream t)
   gptel-model 'claude-sonnet-5)

  ;; OpenAI kept as a secondary backend, explicitly selectable via `gptel-menu'.
  (gptel-make-openai "ChatGPT"
    :key (lambda () (+pass-get-secret "api/openai"))
    :stream t)

  ;; Reusable rewrite/transform directives, selectable from `gptel-rewrite''s
  ;; own transient (its "s" suffix edits/picks the active directive) instead
  ;; of bespoke commands that paste results into a scratch buffer for manual
  ;; copy-paste.
  (setf (alist-get 'clearer gptel-directives)
        "Make the following clearer and more concise while keeping the meaning. Return only the rewritten text.")
  (setf (alist-get 'formal gptel-directives)
        "Rewrite the following in a more formal tone. Return only the rewritten text.")
  (setf (alist-get 'summarize gptel-directives)
        "Summarize the following in 3-5 bullet points."))

(defun my/gptel-add-diagnostics ()
  "Add the current buffer's Flycheck diagnostics to gptel's context.
gptel has no built-in equivalent -- `gptel-add'/`gptel-add-file' cover
region/buffer/project-file context already."
  (interactive)
  (unless (bound-and-true-p flycheck-mode)
    (user-error "Flycheck is not active in this buffer"))
  (require 'flycheck)
  (let ((errors (flycheck-overlay-errors-in (point-min) (point-max)))
        (src (or (buffer-file-name) (buffer-name)))
        (buf (get-buffer-create "*gptel-diagnostics-context*")))
    (unless errors
      (user-error "No Flycheck diagnostics in this buffer"))
    (with-current-buffer buf
      (erase-buffer)
      (insert (format "Flycheck diagnostics for %s:\n\n" src))
      (dolist (err errors)
        (insert (format "%s:%s: %s: %s\n"
                        src
                        (flycheck-error-line err)
                        (flycheck-error-level err)
                        (flycheck-error-message err)))))
    (gptel-context--add-buffer buf)
    (message "Added %d diagnostic(s) to gptel context." (length errors))))

;; AI keys live in `:tools llm''s own `SPC o l' prefix (bound by :config
;; default +bindings, which covers gptel/gptel-send/gptel-add/gptel-add-file/
;; gptel-quick/gptel-rewrite/gptel-menu/gptel-org-set-topic+properties).
;; Only the two commands that map has no equivalent for are added, into the
;; same prefix -- the former `SPC a' namespace and its `embark-act' unbind
;; are gone. See docs/decisions.org ADR-028 (supersedes ADR-003).
;; `my/project-ghostel' is unaffected: still `SPC p t' (see above).
(map! :leader
      :desc "Add diagnostics to context" "o l d" #'my/gptel-add-diagnostics
      :desc "Agent (Claude Code)"        "o l g" #'claude-code-ide-menu)

;; Email: mu4e (+org +gmail +mbsync). Sync via mbsync (isync), send via
;; msmtp. Credentials never live here: the plain-password account resolves
;; via `pass show mail/<label>`, the two Google-backed accounts (one
;; consumer Gmail, one UAlberta Google Workspace) via `oama access <address>`
;; (oama manages the XOAUTH2 refresh cycle pass alone can't do).
;; See docs/decisions.org for the Email ADR and docs/ai/providers.org-style
;; credential map, and ~/.mbsyncrc / ~/.msmtprc for the actual PassCmd /
;; passwordeval wiring (outside the repo, chmod 600).
;; The leader binding is Doom's own default: `SPC o m' / `=mu4e', `SPC o M c'
;; to compose -- no custom map! needed here.
(with-eval-after-load 'mu4e
  (setq sendmail-program (executable-find "msmtp")
        send-mail-function #'smtpmail-send-it
        message-sendmail-f-is-evil t
        message-sendmail-extra-arguments '("--read-envelope-from")
        message-send-mail-function #'message-send-mail-with-sendmail
        ;; Neither personal's nor ualberta's maildir root is literally named
        ;; "gmail" (they're named by account label, not provider), so
        ;; `+mu4e-msg-gmail-p's `(string-match-p "gmail" root-maildir)'
        ;; fallback never catches either one -- both need to be listed here
        ;; explicitly to get the Gmail IMAP integrations (X-GM-LABELS
        ;; retagging for trash/refile/flag, auto-expunge handling). The cdr
        ;; must be the *root maildir* with no leading slash -- what
        ;; `+mu4e-msg-gmail-p' actually computes and compares against.
        ;; Previously only ualberta was listed, and with a leading slash
        ;; ("/ualberta") that never matched the slash-less comparison, so
        ;; this silently never worked for either account; see
        ;; docs/ai/troubleshooting.org::tshoot-mu4e-gmail-p-slash-mismatch.
        +mu4e-gmail-accounts '(("mrniceguyjames@gmail.com" . "personal")
                                ("jcook@ualberta.ca" . "ualberta"))
        ;; Background fetch; per-account maildirs are under ~/.mail/<label>/.
        mu4e-update-interval 60)

  ;; Spam: Gmail already filters spam server-side into "[Gmail]/Spam", and
  ;; mbsync mirrors it locally (Patterns * in ~/.mbsyncrc), so there's
  ;; nothing to "create" there for the personal/ualberta accounts -- just
  ;; give mu4e a way to *use* it, by physically moving the message into it
  ;; over IMAP. Gmail treats a move into "[Gmail]/Spam" as a spam report
  ;; and trains its filter from it, the same way moving into Trash/All Mail
  ;; already works for the built-in trash/refile marks -- deliberately NOT
  ;; using the doom+ mu4e module's X-GM-LABELS retag path (`+mu4e-msg-gmail-p'
  ;; + `+mu4e-gmail-fix-flags-h', fixed above for trash/refile/flag): a spam
  ;; report is exactly the kind of thing a real-mailbox move already handles
  ;; correctly, no retagging needed. tricca (plain IMAP via Gandi, not
  ;; Gmail) has no folder wired up: that account has never synced yet and
  ;; its server-side folder layout (if any spam/junk folder exists at all)
  ;; is unverified.
  ;;
  ;; `s' marks a message as spam, following the same pattern doom+'s mu4e
  ;; module already uses for refile (see its config.el): a plain
  ;; `mu4e--server-move' clearing the New flag.
  (defconst +mu4e-spam-accounts '("personal" "ualberta")
    "Root maildirs with a Gmail-style Spam folder wired up for the `spam' mu4e mark.")

  (defun +mu4e-get-spam-folder (msg)
    "Resolve MSG's account's Gmail Spam folder, e.g. \"/personal/[Gmail]/Spam\".
Errors for any account not listed in `+mu4e-spam-accounts'."
    (let ((root (replace-regexp-in-string
                 "/.*" "" (substring (mu4e-message-field msg :maildir) 1))))
      (if (member root +mu4e-spam-accounts)
          (concat "/" root "/[Gmail]/Spam")
        (mu4e-error "No spam folder configured for the %s account" root))))

  (setf (alist-get 'spam mu4e-marks)
        (list :char '("s" . "☠")
              :prompt "sspam"
              :dyn-target (lambda (_target msg) (+mu4e-get-spam-folder msg))
              :action (lambda (docid _msg target)
                        (mu4e--server-move docid (mu4e--mark-check-target target) "-N"))))

  ;; The stock "Unread messages" bookmark (`u') searches every maildir, so
  ;; unread mail Gmail already filed as spam would otherwise surface right
  ;; next to real unread mail. `maildir:/Spam/' matches any maildir ending
  ;; in "Spam" (see mu-query(7) MAILDIR), which covers both Gmail accounts'
  ;; "[Gmail]/Spam" in one clause.
  (when-let* ((bm (seq-find (lambda (bm) (equal (plist-get bm :name) "Unread messages"))
                             mu4e-bookmarks)))
    (plist-put bm :query "flag:unread AND NOT flag:trashed AND NOT maildir:/Spam/")))

(set-email-account! "personal"
  '((mu4e-sent-folder    . "/personal/[Gmail]/Sent Mail")
    (mu4e-drafts-folder  . "/personal/[Gmail]/Drafts")
    (mu4e-trash-folder   . "/personal/[Gmail]/Trash")
    (mu4e-refile-folder  . "/personal/[Gmail]/All Mail")
    (smtpmail-smtp-user  . "mrniceguyjames@gmail.com")
    (user-mail-address   . "mrniceguyjames@gmail.com")
    (smtpmail-smtp-server . "smtp.gmail.com"))
  t) ;; default account -- confirm this is the intended default

(set-email-account! "ualberta"
  '((mu4e-sent-folder    . "/ualberta/[Gmail]/Sent Mail")
    (mu4e-drafts-folder  . "/ualberta/[Gmail]/Drafts")
    (mu4e-trash-folder   . "/ualberta/[Gmail]/Trash")
    (mu4e-refile-folder  . "/ualberta/[Gmail]/All Mail")
    (smtpmail-smtp-user  . "jcook@ualberta.ca")
    (user-mail-address   . "jcook@ualberta.ca")
    (smtpmail-smtp-server . "smtp.gmail.com")))

(set-email-account! "tricca"
  '((mu4e-sent-folder    . "/tricca/Sent")
    (mu4e-drafts-folder  . "/tricca/Drafts")
    (mu4e-trash-folder   . "/tricca/Trash")
    (mu4e-refile-folder  . "/tricca/Archive")
    (smtpmail-smtp-user  . "jcook@tricca.ca")
    (user-mail-address   . "jcook@tricca.ca")
    (smtpmail-smtp-server . "mail.gandi.net")
    (smtpmail-smtp-service . 465)
    (smtpmail-stream-type  . ssl)))

;; RSS: elfeed (+org +youtube). Feeds are managed as an Org outline at
;; org-directory/elfeed.org (elfeed-org), not as a `elfeed-feeds' list here --
;; see that file for actual subscriptions. `+youtube' adds elfeed-tube
;; (transcript fetching, mpv follow-along -- the mpv-specific keybindings are
;; inert until `mpv' is installed on this system). See docs/decisions.org for
;; the RSS integration ADR.
(map! :leader :desc "RSS (elfeed)" "o r" #'elfeed)

;; Auto-refresh feeds whenever the elfeed search buffer is opened, so `SPC o r'
;; doesn't show a buffer that's stale since the last manual `elfeed-update'.
(add-hook 'elfeed-search-mode-hook #'elfeed-update)

;; App launcher: SPC o L -- raise-or-launch external GUI apps, plus a couple
;; of "the Emacs command *is* the app" bindings (calc, proced) that need no
;; process launching at all. This is a plain process launcher, not a window-
;; manager change -- EXWM itself stays deferred to its own future roadmap
;; phase per ADR-002 (docs/decisions.org). PDFs and images get no binding
;; here: both already auto-open via `find-file'/Dired -- PDFs through the
;; `pdf' module's pdf-tools (once its `epdfinfo' helper has `libpoppler-
;; glib-dev' to compile against), images through the built-in `image-mode'.
(defun my/launch-or-focus (app)
  "Focus a running window for APP, or launch APP as a new process.
APP is used both as the shell command to run and as the (best-effort,
substring) WM_CLASS pattern passed to `xdotool' when looking for an
already-running instance to focus instead of spawning a duplicate. Falls
back to always launching a fresh process if `xdotool' isn't on PATH, or no
matching window is found."
  (interactive)
  (let ((win (and (executable-find "xdotool")
                   (ignore-errors
                     (car (process-lines "xdotool" "search" "--class" app))))))
    (if win
        (call-process "xdotool" nil nil nil "windowactivate" win)
      (start-process app nil app))))

;; Moved off `SPC o l' 2026-08-23: that prefix belongs to `:tools llm' since
;; the module was enabled, and this `:prefix' form was silently replacing the
;; module's whole gptel map (see docs/decisions.org ADR-028).
(map! :leader
      (:prefix ("o L" . "launch")
       :desc "Firefox"                  "f" (cmd! (my/launch-or-focus "firefox"))
       :desc "Discord"                  "d" (cmd! (my/launch-or-focus "discord"))
       :desc "VLC"                      "v" (cmd! (my/launch-or-focus "vlc"))
       :desc "Calculator (calc)"        "c" #'calc
       :desc "Process monitor (proced)" "t" #'proced))

;; Inline completion: Copilot overlay + Next Edit Suggestions.
;; TAB/C-TAB below are copilot.el's own default bindings (`copilot-completion-map'
;; and `copilot-nes-mode-map'), not re-bound here -- both are activated via
;; overlay-local/filtered keymaps that fall through to Corfu/indent/yasnippet
;; when no suggestion is pending (Corfu, not Company, since ADR-021). See
;; docs/ai/keybindings.org for the precedence analysis and docs/decisions.org
;; ADR-007/ADR-021.
(use-package! copilot
  :hook ((prog-mode . copilot-mode)
         (prog-mode . copilot-nes-mode)))

(after! copilot
  (set-face-attribute 'copilot-overlay-face nil
                      :foreground "#9FC59F"  ;; zenburn green+2, bright but still subtle
                      :background 'unspecified))

;; Primary agentic coding workflow: claude-code-ide.el drives the already-
;; installed Claude Code CLI over MCP. Ediff-based review matches this
;; config's existing incumbent (docs/decisions.org ADR-004). Terminal backend
;; migrated from vterm to ghostel 2026-08-17 (docs/decisions.org ADR-014) to
;; get around a vterm/libvterm resize-repaint bug; live-verified to
;; render/resize correctly before this flip, and again via a full from-scratch
;; smoke-test re-run. Vterm itself (module and all its call sites in this
;; config) was removed the same day once ghostel covered every prior use.
;; Settings below are set explicitly even where they match upstream defaults,
;; so an upstream default change doesn't silently change behavior here.
(use-package! claude-code-ide
  :commands (claude-code-ide-menu)
  :init
  (setq claude-code-ide-terminal-backend 'ghostel
        claude-code-ide-diagnostics-backend 'flycheck
        claude-code-ide-use-ide-diff t)
  :config
  (claude-code-ide-emacs-tools-setup))

;; Note management: Vulpea indexes any org entry (file- or heading-level)
;; carrying an `ID' property into its own sqlite database -- titles, tags,
;; id: links, and description-list metadata. Vulpea 2.x is standalone (its
;; Package-Requires names emacsql, not org-roam; v1 was the org-roam layer),
;; so it and org-roam are two independent databases, not a stack. Notes are
;; picked up from `org-directory' (set above) since
;; `vulpea-db-sync-directories' is left at its default. Deferred to first
;; input so it never blocks startup; `vulpea-db-autosync-mode' does the
;; initial database scan in the background and then watches for changes.
(use-package! vulpea
  :defer t :after-call doom-first-input-hook
  :config
  (vulpea-db-autosync-mode +1))

;; org-roam runs alongside Vulpea (docs/decisions.org ADR-027), with Vulpea
;; winning every overlap. Three settings hold that line; each corresponds to
;; a place the two packages would otherwise both answer the same question:
;;
;; 1. Scope. `org-roam-directory' stays at Doom's default (~/org/roam/),
;;    NOT `org-directory'. Vulpea owns the whole tree; org-roam owns one
;;    subdirectory inside it. This also keeps the two autosync watchers off
;;    each other's files for everything outside ~/org/roam/.
;; 2. In-buffer completion. Doom's org-roam config sets
;;    `org-roam-completion-everywhere' to t, which installs a
;;    completion-at-point that offers roam nodes while typing in any org
;;    buffer -- directly competing with `vulpea-insert'. Turned back off.
;; 3. Backlinks. `+org-roam-auto-backlinks-buffer' is nil by default, and is
;;    pinned here so an upstream default-flip can't start auto-opening
;;    org-roam's right-side buffer on top of `my/vulpea-buffer-toggle''s
;;    (both claim :side right; see the vulpea backlinks section below).
;;
;; org-roam's own commands stay reachable under Doom's stock `SPC n r'
;; prefix -- this makes Vulpea primary, it doesn't disable org-roam.
(after! org-roam
  (setq org-roam-completion-everywhere nil
        +org-roam-auto-backlinks-buffer nil))

;; Org Agenda & Capture basics (docs/decisions.org ADR-017). Deliberately
;; minimal per docs/standards.org std-no-scope-creep ("don't build the full
;; Org Agenda system until its own phase") -- this *is* that phase, scoped to
;; agenda-files/TODO-states/capture-templates only, no custom agenda views.
;; `org-agenda-files' covers the whole pre-existing `org-directory' tree
;; (~/org/), including files that predate this project (e.g. `doom.org' has a
;; stray "TODO" headline that isn't really a task) -- a deliberate, informed
;; choice, not an oversight. TODO keywords match this repo's own PROJECT.org
;; convention rather than inventing a second one. Capture templates file into
;; the "Inbox" headline `~/org/todo.org' already had (pre-dating this
;; project); the third creates a real Vulpea-indexed note using the exact
;; org-capture target pattern Vulpea's own docs recommend (`vulpea-create' as
;; the file target, so the note gets an ID/backlinks like any
;; `vulpea-find'-created note would).
(after! org
  (setq org-agenda-files (list org-directory)
        org-todo-keywords
        '((sequence "TODO(t)" "IN-PROGRESS(i)" "BLOCKED(b)" "|" "DONE(d)" "REJECTED(r)"))
        org-capture-templates
        `(("t" "Task" entry
           (file+headline ,(expand-file-name "todo.org" org-directory) "Inbox")
           "* TODO %?\n%U" :empty-lines 1)
          ("n" "Note" entry
           (file+headline ,(expand-file-name "todo.org" org-directory) "Inbox")
           "* %?\n%U" :empty-lines 1)
          ("v" "Vulpea note" plain
           (file ,(lambda ()
                    (vulpea-note-path
                     (vulpea-create (read-string "Title: ")))))
           "%?"))))

;; Vulpea dailies (docs/decisions.org ADR-018): a hand-rolled equivalent of
;; org-roam-dailies -- Vulpea itself has no daily-note concept. Each day is
;; its own real Vulpea file-level note (ID, backlinks, findable via
;; `vulpea-find' like anything else) at org-directory/daily/YYYY-MM-DD.org,
;; created on first visit via `vulpea-create'.
(defun my/vulpea-daily--file (date)
  "Return the daily-note file path for DATE (a \"YYYY-MM-DD\" string)."
  (expand-file-name (format "daily/%s.org" date) org-directory))

(defun my/vulpea-daily--goto (date)
  "Visit the daily note for DATE, creating it via `vulpea-create' if needed."
  (let ((file (my/vulpea-daily--file date)))
    (unless (file-exists-p file)
      (vulpea-create date (format "daily/%s.org" date) :tags '("daily")))
    (find-file file)))

(defun my/vulpea-daily--dates ()
  "Return the existing daily-note dates, sorted chronologically."
  (let ((dir (expand-file-name "daily/" org-directory)))
    (when (file-directory-p dir)
      (sort (mapcar #'file-name-sans-extension
                     (directory-files dir nil "\\`[0-9]\\{4\\}-[0-9]\\{2\\}-[0-9]\\{2\\}\\.org\\'"))
            #'string<))))

(defun my/vulpea-daily--current-date ()
  "Return the date the current buffer's daily note is for, or nil."
  (when-let* ((file (buffer-file-name))
              (dir (expand-file-name "daily/" org-directory)))
    (when (string-prefix-p dir (expand-file-name file))
      (file-name-sans-extension (file-name-nondirectory file)))))

(defun my/vulpea-daily--adjacent (direction)
  "Visit the nearest existing daily note before/after the current one.
DIRECTION is `previous' or `next'."
  (let* ((dates (my/vulpea-daily--dates))
         (current (or (my/vulpea-daily--current-date)
                      (format-time-string "%Y-%m-%d")))
         (candidates (if (eq direction 'previous)
                         (reverse (seq-filter (lambda (d) (string< d current)) dates))
                       (seq-filter (lambda (d) (string> d current)) dates))))
    (if candidates
        (find-file (my/vulpea-daily--file (car candidates)))
      (message "No %s daily note" (if (eq direction 'previous) "earlier" "later")))))

(defun my/vulpea-daily-today ()
  "Open (creating if needed) today's daily note."
  (interactive)
  (my/vulpea-daily--goto (format-time-string "%Y-%m-%d")))

(defun my/vulpea-daily-date ()
  "Open (creating if needed) the daily note for a prompted date."
  (interactive)
  (my/vulpea-daily--goto (format-time-string "%Y-%m-%d" (org-read-date nil t))))

(defun my/vulpea-daily-previous ()
  "Visit the previous existing daily note."
  (interactive)
  (my/vulpea-daily--adjacent 'previous))

(defun my/vulpea-daily-next ()
  "Visit the next existing daily note."
  (interactive)
  (my/vulpea-daily--adjacent 'next))

;; Vulpea backlinks buffer (docs/decisions.org ADR-018): a hand-rolled,
;; deliberately scoped equivalent of org-roam-buffer -- Vulpea only ships
;; jump-to-backlink (`vulpea-find-backlink'), not a live panel. Shows the
;; current note's incoming links only (no unlinked-references section, no
;; citation backlinks). Refreshes on both a window-selection change (moving
;; to a different window) and a window-buffer change (visiting a different
;; note in the *same* window, e.g. via `vulpea-find' or `vulpea-find-backlink'
;; -- the more common case, and the reason both hooks are needed rather than
;; just one).
(defvar my/vulpea-buffer-name "*vulpea-buffer*")

(defvar-local my/vulpea-buffer--shown-id nil
  "ID of the note currently rendered in the Vulpea backlinks buffer.")

(define-derived-mode my/vulpea-buffer-mode special-mode "Vulpea-Backlinks"
  "Major mode for the hand-rolled Vulpea backlinks side buffer.")

(defun my/vulpea-buffer--note-for-window (window)
  "Return the Vulpea note backing WINDOW's buffer's file, or nil."
  (when-let* ((file (buffer-file-name (window-buffer window))))
    (car (vulpea-db-query-by-file-path file 0))))

(defun my/vulpea-buffer--render (note)
  "Render NOTE's backlinks into the Vulpea backlinks buffer."
  (with-current-buffer (get-buffer-create my/vulpea-buffer-name)
    (unless (derived-mode-p 'my/vulpea-buffer-mode)
      (my/vulpea-buffer-mode))
    (let* ((inhibit-read-only t)
           (links (vulpea-db-query-links-to (vulpea-note-id note)))
           (id->note (make-hash-table :test #'equal)))
      (when links
        (dolist (n (vulpea-db-query-by-ids
                    (delete-dups (mapcar (lambda (l) (plist-get l :source)) links))))
          (puthash (vulpea-note-id n) n id->note)))
      (erase-buffer)
      (insert (propertize (vulpea-note-title note) 'face 'org-document-title) "\n\n"
              (format "Backlinks (%d)\n" (length links))
              (make-string 20 ?-) "\n\n")
      (if (null links)
          (insert "No backlinks.\n")
        (dolist (link links)
          (when-let* ((src (gethash (plist-get link :source) id->note)))
            (insert-text-button (vulpea-note-title src)
                                 'action (lambda (_) (vulpea-visit src))
                                 'follow-link t)
            (when-let* ((desc (plist-get link :description)))
              (insert (format "  — %s" desc)))
            (insert "\n"))))
      (goto-char (point-min))
      (setq my/vulpea-buffer--shown-id (vulpea-note-id note)))))

(defun my/vulpea-buffer--maybe-update (&optional _frame)
  "Refresh the Vulpea backlinks buffer for the selected window, if visible."
  (when (get-buffer-window my/vulpea-buffer-name)
    (when-let* ((note (my/vulpea-buffer--note-for-window (selected-window))))
      (unless (equal (vulpea-note-id note)
                     (buffer-local-value 'my/vulpea-buffer--shown-id
                                         (get-buffer my/vulpea-buffer-name)))
        (my/vulpea-buffer--render note)))))

(defun my/vulpea-buffer-toggle ()
  "Toggle a live side window showing backlinks to the current buffer's note."
  (interactive)
  (if-let* ((win (get-buffer-window my/vulpea-buffer-name)))
      (delete-window win)
    (if-let* ((note (my/vulpea-buffer--note-for-window (selected-window))))
        (progn
          (display-buffer-in-side-window
           (get-buffer-create my/vulpea-buffer-name)
           '((side . right) (slot . 0) (window-width . 0.30)))
          (my/vulpea-buffer--render note))
      (message "Current buffer is not a Vulpea note"))))

(add-hook 'window-selection-change-functions #'my/vulpea-buffer--maybe-update)
(add-hook 'window-buffer-change-functions #'my/vulpea-buffer--maybe-update)

(map! :leader
      (:prefix ("n v" . "vulpea")
       :desc "Find note"     "f" #'vulpea-find
       :desc "Find backlink" "b" #'vulpea-find-backlink
       :desc "Insert link"   "i" #'vulpea-insert
       :desc "Full scan"     "s" #'vulpea-db-sync-full-scan
       :desc "Diagnostics"   "d" #'vulpea-doctor
       :desc "Toggle backlinks buffer" "B" #'my/vulpea-buffer-toggle
       :desc "Daily: today"     "j" #'my/vulpea-daily-today
       :desc "Daily: pick date" "J" #'my/vulpea-daily-date
       :desc "Daily: previous"  "p" #'my/vulpea-daily-previous
       :desc "Daily: next"      "n" #'my/vulpea-daily-next))

;; EXWM
;; (defun my/exwm-screen-layout ()
;;   "Configure monitors: external on the left of the laptop."
;;   (start-process-shell-command
;;    "xrandr" nil
;;    ;; External HDMI-1 on the left, laptop eDP-1 on the right
;;    "xrandr --output HDMI-1 --auto --left-of eDP-1 --output eDP-1 --auto --primary"))

;; ;; Apply once at startup
;; (add-hook 'exwm-init-hook #'my/exwm-screen-layout)

;; ;; Optional: re-apply on EXWM restart (only if your EXWM provides this hook)
;; (when (boundp 'exwm-restart-hook)
;;   (add-hook 'exwm-restart-hook #'my/exwm-screen-layout))

;; ;; RandR integration (multi-monitor awareness)
;; (require 'exwm-randr)

;; ;; Re-apply layout when screens change (dock/undock, power cycle, etc.)
;; (add-hook 'exwm-randr-screen-change-hook #'my/exwm-screen-layout)

;; ;; Optional: pin workspaces to monitors
;; ;; 0–4 on HDMI-1 (left), 5–9 on eDP-1 (right)
;; (setq exwm-randr-workspace-output-plist
;;       '(0 "HDMI-1" 1 "HDMI-1" 2 "HDMI-1" 3 "HDMI-1" 4 "HDMI-1"
;;         5 "eDP-1"  6 "eDP-1"  7 "eDP-1"  8 "eDP-1"  9 "eDP-1"))

;; (exwm-randr-mode 1)

;; ;; Make class name the buffer name
;; (add-hook 'exwm-update-class-hook
;;           (lambda ()
;;             (exwm-workspace-rename-buffer exwm-class-name)))

;; ;; Global keybindings.
;; (unless (get 'exwm-input-global-keys 'saved-value)
;;   (setq exwm-input-global-keys
;;         `(
;;           ;; Helpful Commands
;;           ([?\s-/] . exwm-input-release-keyboard)
;;           ([?\s-?] . exwm-reset)
;;           ;; Toggles
;;           ([?\s-F] . exwm-floating-hide)
;;           ([?\s-f] . exwm-floating-toggle-floating)
;;           ([?\s-m] . exwm-layout-toggle-mode-line)
;;           ([f11] . exwm-layout-toggle-fullscreen)
;;           ;; Workspace Management
;;           ([?\s-w] . exwm-workspace-switch)
;;           ([?\s-W] . exwm-workspace-swap)
;;           ([?\s-\C-w] . exwm-workspace-move)
;;           ;; Switch workspace with super+[0-9]
;;           ([?\s-0] . (lambda () (interactive) (exwm-workspace-switch-create 0)))
;;           ([?\s-1] . (lambda () (interactive) (exwm-workspace-switch-create 1)))
;;           ([?\s-2] . (lambda () (interactive) (exwm-workspace-switch-create 2)))
;;           ([?\s-3] . (lambda () (interactive) (exwm-workspace-switch-create 3)))
;;           ([?\s-4] . (lambda () (interactive) (exwm-workspace-switch-create 4)))
;;           ([?\s-5] . (lambda () (interactive) (exwm-workspace-switch-create 5)))
;;           ([?\s-6] . (lambda () (interactive) (exwm-workspace-switch-create 6)))
;;           ([?\s-7] . (lambda () (interactive) (exwm-workspace-switch-create 7)))
;;           ([?\s-8] . (lambda () (interactive) (exwm-workspace-switch-create 8)))
;;           ([?\s-9] . (lambda () (interactive) (exwm-workspace-switch-create 9)))
;;           ;; Window Management
;;           ([?\s-\C-v] . evil-window-vsplit)
;;           ([?\s-z] . evil-window-split)
;;           ([?\s-b] . ibuffer)
;;           ([?\s-B] . kill-current-buffer)
;;           ([?\s-C] . +workspace/close-window-or-workspace)
;;           ([?\s-x] . doom/open-scratch-buffer)
;;           ;; Change window focus with super+h,j,k,l
;;           ([?\s-h] . evil-window-left)
;;           ([?\s-j] . evil-window-down)
;;           ([?\s-k] . evil-window-up)
;;           ([?\s-l] . evil-window-right)
;;           ;; Move windows around using super+shift+h,j,k,l
;;           ([?\s-H] . +evil/window-move-left)
;;           ([?\s-J] . +evil/window-move-down)
;;           ([?\s-K] . +evil/window-move-up)
;;           ([?\s-L] . +evil/window-move-right)
;;           ;; Essential Programs
;;           ([?\s-d] . dired)
;;           ([?\s-t] . (lambda () (interactive)
;;                        (start-process-shell-command "terminal" "*terminal*" "xfce4-terminal")))
;;           ;; Launch application.
;;           ([?\M-\s-7] . (lambda (command)
;;                           (interactive (list (read-shell-command "$ ")))
;;                           (start-process-shell-command command nil command))))))

;; ;; Line-editing shortcuts
;; (unless (get 'exwm-input-simulation-keys 'saved-value)
;;   (setq exwm-input-simulation-keys
;;         '(([?\C-b] . [left])
;;           ([?\C-f] . [right])
;;           ([?\C-p] . [up])
;;           ([?\C-n] . [down])
;;           ([?\C-a] . [home])
;;           ([?\C-e] . [end])
;;           ([?\M-v] . [prior])
;;           ([?\C-v] . [next])
;;           ([?\C-d] . [delete])
;;           ([?\C-k] . [S-end delete])
;;           ([?\s-c] . [?\C-c])
;;           ([?\s-v] . [?\C-v]))))

;; ;; Enable EXWM
;; (exwm-enable)

;; ;; Open Workspaces and start programs?
